stryker-mutator/stryker-net

- README.md
- appveyor.yml
- appveyor_nugetpack.yml
- src/Stryker.CLI/README.md
- src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
- src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
To prepare the codebase for automatic releases trough appveyor. The nuget pack and nuget push command will use the info from the .csproj files.
> Fix: update project info for NuGet pack

- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFileTests.cs
- src/Stryker.CLI/Stryker.CLI.UnitTest/Stryker.CLI.UnitTest.csproj
- src/Stryker.CLI/Stryker.CLI.UnitTest/StrykerCLITests.cs
- src/Stryker.CLI/Stryker.CLI/CLIOptions.cs
- src/Stryker.CLI/Stryker.CLI/OptionsBuilder.cs
- src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
Check if there is a config file called stryker-config.json or with the given name. else it should use the default 
Fixes #101
> Check if there is a config file, else use default

- src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
- src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
Removed PackageVersion, AssemblyVersion, FileVersion and InformationalVersion properties from csproj's because they default to the value of the Version property.
> chore(build): remove additional version properties

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectFileReaderTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs
I decided to try running Stryker.NET on Linux, and it turned out to be really close to ready.  This pull request fixes what looks like the last remaining issue, which is that project file paths were always returned with the Windows directory separators. Fixes #120
> fix(dependency-resolver): Support backslash in ProjectReferences on Linux

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectFileReaderTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs
-Add multiple framework support to ProjectFileReader.
-Add tests to ensure expected functionality and to ensure no regressions
Fixes #130, if a .csproj contains multiple framework support, currently Stryker breaks with a NullReference Exception.  This change inserts a stop-gap that instructs Stryker to use the first found framework.
> feat(build): Add multiple framework support

- src/Stryker.CLI/Stryker.CLI/CLIOptions.cs
- src/Stryker.Core/Stryker.Core.UnitTest/AssertExtensions.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Compiling/CompilingProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/AssemblyReferenceResolverTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs
- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
- src/Stryker.Core/Stryker.Core/Initialisation/AssemblyReferenceResolver.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectComponents/IReadOnlyInputComponent.cs
- src/Stryker.Core/Stryker.Core/Mutants/Mutant.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestExecutor.cs
- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestInput.cs
- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs
- src/Stryker.Core/Stryker.Core/Reporters/IReporter.cs
- src/Stryker.Core/Stryker.Core/StrykerRunner.cs
- src/Stryker.Core/Stryker.Core/Testing/ProcessExecutor.cs
I polish comments for better understanding.
I have doubt about 'mutationtest' term, but in all repos scope 'mutation test' is more related.
I hope, that PR can made project a little better.
> chore: fix minor spelling issues and typos in comments and log messages

- src/Stryker.Core/Stryker.Core.UnitTest/Compiling/RollbackProcessTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
Reopen PR so someone else can pick up the changes that were left since @B1tF8er no longer has time to fix this. No sense throwing away the changes already made.
Fixes #145 Reopened from #148
> fix(mutating): Make sure a broken mutation does not exist twice, so that we can roll back the mutation (#145)

- azure-pipelines.yml
Sets the build number to `stryker-net-0.3.0.x` instead of the current date with a revision number.
> build: Set build number to version number

- integrationtests/IntegrationTests/Stryker.Core.IntegrationTest/ExampleProject/ExampleProject.XUnit/ExampleProject.XUnit.csproj
In the exampleproject a reference to the actual nuget package was present. This broke the integrationtest, but only after version 0.4 was released. The reference is still unneeded and should be removed. 
The fixing of 0.4 installation has already been adressed in #218
> Remove reference to Stryker nuget package

- src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
This string missed interpolation, so it actually printed:
```
Final mutation score: {results.mutationScore} under breaking threshold value {options.ThresholdOptions.ThresholdBreak},                                
,setting exit code to 1 (failure).
Improve the mutation score or set the `threshold-break` value lower to prevent this error in the future
```
Now it prints:
```
Final mutation score: 11 under breaking threshold value 50,                                
Setting exit code to 1 (failure).
Improve the mutation score or set the `threshold-break` value lower to prevent this error in the future
```
> Fix string interpolation mistake

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectComponents/ProjectComponentTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/ConsoleDotReporterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Progress/MutantsResultReporterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Progress/ProgressReporterTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectComponents/ProjectComponent.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantStatus.cs
- src/Stryker.Core/Stryker.Core/Reporters/ConsoleDotProgressReporter.cs
- src/Stryker.Core/Stryker.Core/Reporters/ConsoleReportReporter.cs
- src/Stryker.Core/Stryker.Core/Reporters/Progress/ConsoleOneLineLoggerFactory.cs
- src/Stryker.Core/Stryker.Core/Reporters/Progress/MutantsResultReporter.cs
- src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressReporter.cs
Logging template without timestamp for oneline logger. Looks cleaner.
Tests cleanup.
I have removed MutantStatus.RuntimeError since it cannot be detected anyway. It always showed count 0.
> fix(logging): Clean up oneline logger output by removing timestamp

- integrationtests/IntegrationTests/Stryker.Core.IntegrationTest/ExampleProject/ExampleProject/LinqMutatorExamples.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/LinqMutatorTest.cs
- src/Stryker.Core/Stryker.Core/Mutators/LinqMutator.cs
Linq mutator now targets MemberAccessExpression instead of IdentifierName
Closes #250
> fix(LinqMutator): Linq mutator mutates only method invocations

- README.md
The names changed in a previous PR but were forgotten on the main readme file
> doc(Mutator names): Update mutator names in readme

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectFileReaderTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestProcessTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectFile.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectInfo.cs
- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestInput.cs
If present and true or absent, build generate files to bin/Mode/targetFramework (ex: /bin/Deug/netcoreapp2.0)
Is set to false, build generate file to bin/Mode (ex: bin/Debug)
this fix the issue when AppendTargetFrameworkToOutputPath is set to false resulting to an System.UnauthorizedAccessException
Fix #272
> Handle AppendTargetFrameworkToOutputPath csproj property

- integrationtests/IntegrationTests/ExampleProject.XUnit/UnsafeCodeTest.cs
- integrationtests/IntegrationTests/ExampleProject/ExampleProject.csproj
- integrationtests/IntegrationTests/ExampleProject/UnsafeCode.cs
- src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs
To prevent errors during recompile, the option /allowUnsafe is set to true
> feat(unsafe blocks): recompile with unsafe=true

- src/Stryker.Core/Stryker.Core.UnitTest/Compiling/CompilingProcessTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs
- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
On large projects not all compilation errors are returned by the Roslyn compiler on the first compilation. The rollback process does not rollback all broken mutations on the rirst try. This PR adds a seconds rollback step to also catch all missed compilation errors.
closes #304 and possibly #18
> fix(Missed compilation erros): Rollback two times instead of one

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_SyntaxShouldBe_IfStatement_OUT.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs
Local functions were mutated with if statements. Now only their body is mutated. This leaves their scope unchanged fixing a bug. 
closes #321
> Fix(Local functions): Local functions are mutated correctly

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_SyntaxShouldBe_ConditionalStatement_IN.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_SyntaxShouldBe_ConditionalStatement_OUT.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs
closes #339 
Was not able to break up the `Mutate(SyntaxNode)` method since it has a high complexity in object references. We might need to look for a way to split this method.
> fix(Lambda bug): Improved mutation algorithm

- .gitignore
- src/Stryker.CLI/Stryker.CLI.UnitTest/Stryker.CLI.UnitTest.csproj
- src/Stryker.Core/Stryker.Core.UnitTest/AssertExtensions.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_FromActualProject_IN.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_FromActualProject_OUT.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_KnownComplexCases_IN.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_KnownComplexCases_OUT.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
- src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs
- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs
- src/Stryker.Core/Stryker.Core/Mutators/AssignmentStatementMutator.cs
- src/Stryker.Core/Stryker.Core/Mutators/BinaryExpressionMutator.cs
- src/Stryker.Core/Stryker.Core/Mutators/LinqMutator.cs
- src/Stryker.Core/Stryker.Core/SyntaxHelper.cs
- identify slightly more mutants that in the current release
- avoid generating known to fail mutants (e.g. default value for parameter or string concatenation)
- dump CompileError mutants in devmode
> fix(Missing mutations): Improve mutation algorithm to find more mutants

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_FromActualProject_IN.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_FromActualProject_OUT.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs
closes #395 
Resolution was to skip the iteration in the foreach. If the iteration continues the same node will be mutated again. Somehow the mutations ended up only once in code. But twice in the mutants array.
Fixed unit tests too.
> fix(Double mutations): On invocation expressions

- src/Stryker.Core/Stryker.Core.UnitTest/Compiling/RollbackProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/AddMutator.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantPlacerTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_AssignStatements_OUT.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_FromActualProject_OUT.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_IfStatementsShouldBe_Nested_OUT.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_KnownComplexCases_IN.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_KnownComplexCases_OUT.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_SyntaxShouldBe_ConditionalStatement_OUT.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_SyntaxShouldBe_IfStatement_OUT.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantPlacer.cs
Fixes #412 and **should** fix #411.
Ensure mutation control is applied close to the mutant, usually next to the mutated expression part. This should fix #411 (tbc), it may slightly increase the number of mutants. As it changes the order of mutant generation, it impacts mutant id.
Add tolerance for null Condition in ForStatementSyntax.
> fix(Handeling statements): ForStatements and ExpressionStatement mutated correctly

- src/Stryker.CLI/Stryker.CLI.UnitTest/StrykerCLITests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestProcessTests.cs
- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs
- src/Stryker.Core/Stryker.Core/StrykerRunResult.cs
Hi, 
I'm currently starting a new project and I disabled string mutations, It happened that those were only mutations in my project. So all mutations were skipped. I was surprised when Stryker exited with code 1, instead of 0, even that I had Threshold Break set to 0. 
I think that when there are no tests to run exit code should be 0 not 1. The issue, that I found is passing mutation score as nullable decimal `decimal?` to the `StrykerRunResult` when there are no mutations to run.
```csharp
public bool IsScoreAboveThresholdBreak()
{
// Check if the mutation score is not below the threshold break
//          null     >=   0  this is not true.
return MutationScore >= _options.Thresholds.Break;
}
```
I added if statement that checks if `MutationScore` is `null`, and checks if Threshold.Break …
> feat(exclusions): Warn user on all mutations excluded

- src/Stryker.CLI/README.md
Fix for docs found in https://github.com/stryker-mutator/stryker-net/issues/434.
> docs(readme.md): example fix

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InputFileResolverTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs
Hi, just thought maybe this error formatting 
```
_____ _              _               _   _ ______ _______
/ ____| |            | |             | \ | |  ____|__   __|
| (___ | |_ _ __ _   _| | _____ _ __  |  \| | |__     | |
\___ \| __| '__| | | | |/ / _ \ '__| | . ` |  __|    | |
____) | |_| |  | |_| |   <  __/ |    | |\  | |____   | |
|_____/ \__|_|   \__, |_|\_\___|_| (_)|_| \_|______|  |_|
__/ |
|___/
Version 0.9.0 (beta)
[21:19:14 INF] Time Elapsed 00:00:00.1008880
Stryker.NET failed to mutate your project. For more information see the logs below:
Expected exactly one .csproj file, found more than one:
/Users/robertlyson/projects/TestProject2/TestProject2/TestProject2.csproj
/Users/robertlyson/projects/TestProject2/TestProject2/published/TestProject2.csproj
Please fix your project …
```
> feat(input file resolver): directory contains more than one csproj

- src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
- src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
Hi 👋,
PR to address https://github.com/stryker-mutator/stryker-net/issues/410.
At a first glance this looks a little bit clumsy(LICENS*)
```
<ItemGroup>
<None Include="..\..\..\LICENS*" Pack="true" PackagePath="" />
</ItemGroup>
```
but this is a work around for [known issue](https://github.com/NuGet/Home/issues/7601) allowing you to include license file which doesn't have an extension.
> chore(nuget): license

- src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
- src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
Fixes #436.
Updated System.IO.Abstractions to 4.0.11 but all tests were passing locally, so this is something different from #431 #432 #433.
Creating this MR to see how it looks like in CI.
> build(deps): bump System.IO.Abstractions from 3.1.1 to 4.0.11

- src/Stryker.Core/Stryker.Core.UnitTest/Compiling/CompilingProcessTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs
The CompilingProcess has a hard-coded three retries to fix any
compiler errors that are fixed by recompiling. Instead, loop until
the recompile works, or until the recompile fails 100 times in a row.
Thanks to @Mobrockers for the assistance in with the variable
names to properly run the recompile.
Resolves one issue for #462.
> feat(rollback mutations): Recompile 100 times

- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
This should make more clear to users that stryker fails due to other problems than wrong mutations.
> chore(Error messages): Improve error messages for rollback process

- docs/Configuration.md
- docs/Reporters.md
- src/Stryker.CLI/Stryker.CLI/CLIOptions.cs
- src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs
- src/Stryker.Core/Stryker.Core/Reporters/Reporter.cs
- src/Stryker.Core/Stryker.Core/Reporters/ReporterFactory.cs
Reporter names ConsoleReport, ConsoleProgressBar, ConsoleProgressDots replaced with cleartext, progress, dots.
Deprecated old names in help text and warn user about new reporter names
Fix #503
> fix(reporter names): Improve reporter names

- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/AssignmentStatementMutatorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Progress/ProgressBarReporterTests.cs
- src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressBarReporter.cs
After a stryker run on stryker I noticed some missing test cases. Also I could refactor the ProgressBarReporter a lot. This is mainly thanks to stryker stopping at 0 mutations. The Reporter doesn't need to check for null checks anymore.
> chore(Test): Improve ProgressBarReporter and Assignmentstatement tests

- src/Stryker.DataCollector/Stryker.DataCollector/Stryker.DataCollector.csproj
This one was missed because the project did not yet exist.
> deps: Update testplatform objectmodel in datacollector

- src/Stryker.DataCollector/Stryker.DataCollector/CommunicationServer.cs
This PR contains only the fix for the problem with code coverage capture and Net Full Framework.
The problem seems to be that the name built for the pipe looked like an URL and triggered some security checks that ultimately prevented the pipe to be created.
> Fix: coverage failing on net full framework

- src/Stryker.CLI/Stryker.CLI/CLIOption.cs
- src/Stryker.CLI/Stryker.CLI/CLIOptions.cs
- src/Stryker.CLI/Stryker.CLI/OptionsBuilder.cs
- src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
- src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/CoverageCaptureTests.cs
Fixes #278 
This is basically an in-place switch as McMaster.Extensions.CommandLineUtils is a fork of Microsoft.Extensions.CommandLineUtils. No code has been changed yet.
> chore: Switch from Microsoft.Extensions.CommandLineUtils to McMaster.Extensions.CommandLineUtils

- src/Stryker.Core/Stryker.Core.UnitTest/Compiling/CompilingProcessTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs
Fix issue #643: identify when there is a general build failure (no location provided in error) and interrupts stryker in a graceful fashion
> feat: Fail gracefully when compile diagnostics indicate a general build error

- docs/Mutators.md
- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/StringEmptyMutatorTests.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutators/StringEmptyMutator.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
Added a mutator that mutates the member access to `string.Empty` to a string literal that is not empty (`"Stryker was here!"`).
This resolves #641.
> feat(string mutator): Mutate string.Empty to string literal "Stryker was here!"

- src/Stryker.Core/Stryker.Core.UnitTest/Compiling/CompilingProcessTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs
- src/Stryker.Core/Stryker.Core/Exceptions/StrykerCompilationException.cs
Stryker failed to compile but also had a warning diagnostics error with location None. This warning was not the cause of the compilation failure. Stryker should not fail on warning diagnostics.
> fix: Dont fail compiling on warning diagnostics

- src/Stryker.Core/Stryker.Core.UnitTest/stryker-config.json
- src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs
fixes #716 
Nullable context is a C# 8 feature that has to be anabled in the compiler. On older project this produces a lot of warnings but should not produce any errors. As Stryker only looks at errors this should run fine.
> feat(sharp8.0 nullable): Compile with c# 8 nullable feature enabled

- src/Stryker.Core/Stryker.Core/Logging/ApplicationLogging.cs
The generic method throws an exception with the new Microsoft.Extensions.Logging version. This exception is not catched, thus Stryker crashes.
Change generic logging to non-generic logging in application logging. Now the deprecation warning is logged as expected and Stryker continues.
> fix(strykerrunner logging): Use non-generic non-reflection ILogger.Log to log startup logging

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InputFileResolverTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestRunnersShould.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectInfo.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
> fix(vstest): Correctly determine targetframework for vstest configuration

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialTestProcessTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectInfo.cs
Correctly extract where the aggregated version is two numbers.
net48 would end up as 4..8 instead of 4.8 due to double if
> fix(targetframeworkversion extraction): Correctly extract aggregated framework versions

- docs/Configuration.md
While working on a project with Stryker, I noticed that the option
ignore-methods was missing from the config, but it did work when I tried
it. So that's why I decided to add it in.
> docs(docs/Configuration.md) Add example config option

- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestRunnersShould.cs
- src/Stryker.Core/Stryker.Core/TestRunners/TestCoverageInfos.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/RunEventHandler.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
This a defensive fix for issue #843. As discussed, when Stryker detects dynamic test case(s) it ensures each mutant is tested against those to prevent false survivor/non covered.
The 'timeout' detection logic has been revised for VsTest: we rely on the 'aborted' flag, as the number of testresults can be misleading when test cases are dynamic.
Minor refactoring/simplification were done along the way.
> feat(coverage analysis): Implement defensive heuristics to cover when incorrect number of dynamic test cases are reported by testframework

- src/Stryker.Core/Stryker.Core/Initialisation/ProjectInfo.cs
- src/Stryker.Core/Stryker.Core/TestRunners/TestCoverageInfos.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/RunEventHandler.cs
Throws an exception with an explicit error message when failing to parse net framework version from the csproj
Fix #861
> feat(initialisation): Fail gracefully on incorrect targetframework in csproj

- src/Stryker.Core/Stryker.Core.UnitTest/Compiling/CompilingProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Compiling/RollbackProcessTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs
- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
Fix #916 
Fix #929
Fix consists ensuring exception are raised only on the **last** attempt to compile.
This required adding this information (isLastAttempt) across a few calls and update related tests
> fix(rollback): Only crash out of stryker run after last rollback retry attempt 

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs
closes #642 
Adds a return default statement to the end of each method to prevent the not all code paths return a value error.
> feat(mutation placing): Return default(T) for non-void methods

- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/ExcludeFromCodeCoverageFilterTests.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/ExcludeFromCodeCoverageFilter.cs
- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs
If you choose to exclude something from coverage I think it makes sense to also exclude it from mutation testing.
> feat(mutation exclusion): mutants with ExcludeFromCodeCoverage attribute

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs
Since #958 linespans have been wrong. That was seen in the html report.
It turned out that the return default should be placed after mutating a node and not before. Adding the return default messed up the syntax tree inside the mutations. 
Clearly the unit tests we currently have for linespans were not sufficient so I added another one that detects the current flaw.
closes #974
> feat(mutation placing): Return default(T) after placing mutation to preserve linespans

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core/SyntaxHelper.cs
This excludes EnumMemberDeclaration nodes from the nodes to be mutated, which will avoid compiler errors due to the mutation engine generating non-constant code at a place where constants must be used.
> fix: avoid mutating enum member declarations (fixes #1016)

- azure-pipelines.yml
So that we can track differences over package versions instead of every build
> chore(build): Use package version for sonarcloud project version

- README.md
- docs/Mutators.md
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/ArrayCreationMutatorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/InitializerMutatorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/ObjectCreationMutatorTests.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutators/ArrayCreationMutator.cs
- src/Stryker.Core/Stryker.Core/Mutators/InitializerMutator.cs
- src/Stryker.Core/Stryker.Core/Mutators/Mutator.cs
- src/Stryker.Core/Stryker.Core/Mutators/ObjectCreationMutator.cs
This PR adds mutators for collections and arrays. 
I skipped the implicid array for now is it results in compile errors when mutated. We could mutate it by resolving its type and converting it to a typed array in the mutation. I'll create an issue for that.
> feat(Collection initializer mutator): Add mutator for collections and arrays

- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/DiffMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/MutantFilterFactoryTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
- src/Stryker.Core/Stryker.Core/MutantFilters/BroadcastMutantFilter.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/DiffMutantFilter.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/MutantFilterFactory.cs
- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs
closes #1054 
After merging this PR the following things will be refactored:
* Resposibility of creating `MutantFilters` is moved to a seperate `MutantFilterFactory`.
* Looping over the `MutantFitlers` no longer happens in `MutationTestProcess` but is done using a `BroadcastMutantFilter`.
* The `DiffMutantFilter` no longer is responsible for checking whether the `Diff` feature is enabled.
> refactor(MutantFilters): Add MutantFilterFactory and BroadcastMutantFilter

- docs/Configuration.md
Apparently it was hard to find the config file section. We want people to use this feature so I'd like the section to move to the top and added to the TOC.
> docs: Move config file section to the top of the configuration docs

- azure-pipelines.yml
- pipeline-templates/prepare-integration-test-steps.yml
- pipeline-templates/run-integration-test-steps.yml
Fixes issue related to running global dotnet tools right after installing it on Azure Devops pipelines.
Issue and implemented solution are further here: https://github.com/dotnet/sdk/issues/8999
As of my experienced with this same issue on some other pipelines it seems to occur in "most of runs" but not in "all the runs". Still this solution of adding the `tool path` seems to solve it for good.
- **Broken pipeline run:**
https://dev.azure.com/stryker-mutator/Stryker/_build/results?buildId=5287&view=logs&j=6d77c950-6c97-5c0c-ab3e-a9679c1574a4&t=09a0e093-6c57-5708-b0cb-1cd3cc660dca
- **Task - Install dotnet-stryker:**
```
Since you just installed the .NET Core SDK, you will need to reopen the Command Prompt window before running the tool you installed.
```
- **Task - Run Stryker on …
> fix(pipelines): Fix issue with global dotnet tools

- azure-pipelines.yml
There was a missing space between the calling of stryker and the first argument that is causing the pipeline to break.
https://dev.azure.com/stryker-mutator/Stryker/_build/results?buildId=5322&view=logs&j=6d77c950-6c97-5c0c-ab3e-a9679c1574a4&t=6be46d81-717b-5e63-da84-91412b35485c
**Task - Run Stryker on Stryker.Core**
```
'D:\a\1/tools/dotnet-stryker--reporters' is not recognized as an internal or external command,
```
> fix(pipeline): Fix typo wich is breaking the pipeline

- docs/Configuration.md
Improves documentation on how the diff feature actually works. 
Seems like some people (including myself) were not understanding the expected behavior of this feature, as ir can be seen in these issues: #1160 #1180
> docs(diff config) Extends documentation on diff

- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/ClearTextReporterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/ClearTextTreeReporterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/ReporterFactoryTests.cs
- src/Stryker.Core/Stryker.Core/ProjectComponents/FolderComposite.cs
- src/Stryker.Core/Stryker.Core/Reporters/ClearTextReporter.cs
- src/Stryker.Core/Stryker.Core/Reporters/ClearTextTreeReporter.cs
- src/Stryker.Core/Stryker.Core/Reporters/Reporter.cs
- src/Stryker.Core/Stryker.Core/Reporters/ReporterFactory.cs
* Renamed `ClearTextReporter` to `ClearTextTreeReporter`
* Added table report as `ClearTextReporter`
To get a "All files" line, I needed the root folder in the reporter, that was explicitly skipped previously.
This led to some changes (/improvements) to the tree report
* Show root folder with totals in tree
* Move root folder files to root in tree report
Ready for your feedback. 😄 
Should close #1238
> Implement console table report

- .github/ISSUE_TEMPLATE/config.yml
> chore: Add issue template configuration

- src/Stryker.CLI/Stryker.CLI.UnitTest/StrykerCLITests.cs
- src/Stryker.CLI/Stryker.CLI/CLIOptions.cs
closes #1230 
breaks: Parameter GitSource is replaced with GitDiffTarget
> feat(diff compare): Rename parameter git source to git diff target

- docs/Configuration.md
- docs/Mutators.md
- docs/Reporters.md
- docs/Stryker-in-pipeline.md
🙋‍♀️! This PR does a couple things with documentation:
- Fix some links to be relative instead of from the root
- Removes the table of contents. I can add them back if you want, but Docusaurus already has TOC's in the side
- Add a title meta-header to the `Stryker-in-pipeline.md`. The other files have nice capitalized names so they don't need it.
- Add custom-edit-urls to fix 'Edit this page' links
> docs: update docs for new website

- src/Stryker.RegexMutators/Stryker.RegexMutators.UnitTest/Mutators/LookAroundMutatorTest.cs
- src/Stryker.RegexMutators/Stryker.RegexMutators/Mutators/LookAroundMutator.cs
- src/Stryker.RegexMutators/Stryker.RegexMutators/RegexMutantOrchestrator.cs
In regex there is a way to match something, only if it is preceded or proceded by a group.
For example: (?<=foo)bar will match the word bar in foobar, but won't match bar in minibar.
This mutator flips these regexes to check at the end instead of beginning, and to ensure
that it does NOT start with the group. It flips the check.
Closes #1278
> Add regex look ahead and behind mutators

- docs/Configuration.md
Related to #1077
Added a notice that the 'specify testrunner' option will be depracted in version 1.0
> Add deprecation notice for --test-runner option in documentation

- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/DiffMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/DiffMutantFilter.cs
Fix #1290:
- check `CoveringTests.Tests` list for null before access - no check is added for `CoveringTests`, since it has a property initializer in `Mutant` class - the check is needed for compiler error mutants, which won't have any coverage info;
- do not `break` on first processed mutant;
- update tests to cover scenarios above;
- some whitespaces changes enforced by `.editorconfig` - can rollback if needed.
> fix(Diff mutant filter): prevent NPE for compiler error mutants (#1290)

- docs/sidebar.json
As discussed, this will be used to render the sidebar on the website.
The `sidebar.json` (or `sidebar.js` if you prefer a node module) should contain a valid [sidebar object](https://v2.docusaurus.io/docs/docs-introduction#sidebar-object). The document root is `stryker-net`, so [document ids](https://v2.docusaurus.io/docs/docs-introduction#document-id) should be prefixed with that.
> docs(sidebar): add custom sidebar

- docs/sidebar.json
- docs/technical-reference/Introduction.md
- docs/technical-reference/Mutant-schemata.md
- docs/technical-reference/Research.md
This moves the technical references from the wiki to the docs. So they are also displayed on the website
> Create technical references

- integrationtest/ValidationProject/Validation.csproj
- src/Stryker.CLI/Stryker.CLI.UnitTest/Stryker.CLI.UnitTest.csproj
- src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
- src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
- src/Stryker.CLI/Stryker.CLI/packages.lock.json
- src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
- src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
- src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
- src/Stryker.Core/Stryker.Core/packages.lock.json
- src/Stryker.DataCollector/Stryker.DataCollector/Stryker.DataCollector.csproj
- src/Stryker.RegexMutators/Stryker.RegexMutators.UnitTest/Stryker.RegexMutators.UnitTest.csproj
- src/Stryker.RegexMutators/Stryker.RegexMutators.UnitTest/packages.lock.json
- src/Stryker.RegexMutators/Stryker.RegexMutators/Stryker.RegexMutators.csproj
- src/Stryker.RegexMutators/Stryker.RegexMutators/packages.lock.json
Breaks dotnet 3.1 runtime no longer used to run stryker (install dotnet 5 runtime)
> feat: update targetframework from netcoreapp3.1 to net5.0

- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs
Suggesting this after I noticed a message `Mutations will be tested in 10 test runs instead of 10.` :)
Discard if this actually represents a more serious problem.
> Improved debug message.

- integrationtest/TargetProjects/NetFramework/FullFrameworkApp/FullFrameworkApp.csproj
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
- src/Stryker.Core/Stryker.Core/ToolHelpers/VsTestHelper.cs
> fix: Default vstest extensions are no longer required on the filesystem

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/EndingReturnEngine.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantPlacer.cs
Bring 2 fixes:
1 : successfully rollback process can now rollback added `return default(x)`, as well as accessor expression to body form (no unit test)
2: add `yield return default(x)` to iteration method having only `yield break`(but no `yield return`) (unit test)
> fix(mutating): Place yield return instead of yield return default(type) for yield break

- src/Stryker.Core/Stryker.Core.UnitTest/StrykerRunnerTests.cs
- src/Stryker.Core/Stryker.Core/StrykerRunner.cs
Filters were run after reports, which caused the report to not include information about ignored mutants.
Running filters before reports fixes the issue.
Before:
```
[13:23:18 INF] 1     mutants got status CompileError. Reason: Mutant caused compile errors
[13:23:18 INF] 7     mutants got status NoCoverage.   Reason: Mutant has no test coverage
[13:23:18 INF] 8     total mutants are skipped for the above mentioned reasons
[13:23:18 INF] 97    total mutants will be tested
███████████████████████████████████████████████████████████████████████████████████████████████████████████
100.00% │ Testing mutant 95 / 95 │ K 88 │ S 0 │ T 7 │ ~0m 00s │
```
After:
```
[14:09:51 INF] 1     mutants got status CompileError. Reason: Mutant caused compile errors
[14:09:51 INF] 7     mutants got status …
```
> fix(filtered mutants reporter): OnMutantsCreated was executed before filtering mutants

- src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
- src/Stryker.Core/Stryker.Core.UnitTest/xunit.runner.json
I observed that one of the issues was related to the static `JsonReport._report` field. It would be better to get rid of this static caching, by passing the state around explicitly instead, but for now, fixing the flaky tests is probably still a good idea.
I've had the test running with `while dotnet test --no-build; do :; done` for several minutes now without failure.
> Fix flaky tests by not running them in parallel

- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/StrykerVstestHostLauncher.cs
Disable DiffEngine so that approval tests frameworks such as [Verify](https://github.com/VerifyTests/Verify) or [ApprovalTests.Net](https://github.com/approvals/ApprovalTests.Net) (which both use DiffEngine under the hood) don't launch a diffing tool GUI on each failed test.
> Automatically disable DiffEngine when running tests

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantPlacerTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
- src/Stryker.Core/Stryker.Core/Helpers/RoslynHelper.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/AccessorExpressionToBodyEngine.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/BaseEngine.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/ConditionalInstrumentationEngine.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/DefaultInitializationEngine.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/EndingReturnEngine.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/ExpressionMethodToBodyEngine.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/IfInstrumentationEngine.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/PropertyExpressionToBodyEngine.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/StaticInstrumentationEngine.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpMutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantPlacer.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutationContext.cs
- src/Stryker.Core/Stryker.Core/Mutants/NodeOrchestrators/BaseMethodDeclarationOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/NodeOrchestrators/MemberDeclarationOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/NodeOrchestrators/StaticFieldDeclarationDeclarationOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/NodeOrchestrators/StaticFieldDeclarationOrchestrator.cs
Include several fixes and one improvement:
1. Ensure helpers are properly rollbacked and add unit test to prevent regression (issues #1511, #1512).
1. Stryker drops any pending mutants during mutation orchestrating when moving to the next member definition (issue #1527)
1. Stryker injects initialization to default value for all out parameters (at the beginning of methods). This should reduce compile error mutants (should improve #1511 and #1512).
Also refactored injection engine testing, fixed some error messages and improved some naming.
Fixes #1511, #1512, #1527
> fix(mutation orchestration): rollback of helpers and faulty array initializers to prevent unrecoverable compile errors

- src/Stryker.Core/Stryker.Core.UnitTest/StrykerRunnerTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectInfo.cs
- src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs
- src/Stryker.Core/Stryker.Core/StrykerRunner.cs
Fix #1515 
Unit test MutantOrchestratorTests.ShouldNotAddReturnDefaultToEnumerationMethods is failing for me locally but it looks like just whitespace differences in the result.
> feat: Cache and restore unmutated assembly so rebuild is not needed after mutation test

- src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
VS often adds these settings when u change certain settings in the project properties. but they are the default and not required
> Redundant csproj settings

- src/Stryker.CLI/Stryker.CLI.UnitTest/Stryker.CLI.UnitTest.csproj
- src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
- src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
- src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
- src/Stryker.RegexMutators/Stryker.RegexMutators.UnitTest/Stryker.RegexMutators.UnitTest.csproj
- src/Stryker.RegexMutators/Stryker.RegexMutators.UnitTest/packages.lock.json
unfortunately the xunit and xunit.runner.visualstudio packages are not kept in version sync. so there is no value in using a shared version property for them
> split xunit and xunit.runner.visualstudio packages

- src/Stryker.Core/Stryker.Core.UnitTest/Compiling/RollbackProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
- src/Stryker.Core/Stryker.Core/Helpers/RoslynHelper.cs
- src/Stryker.Core/Stryker.Core/Mutants/NodeOrchestrators/PropertyDeclarationOrchestrator.cs
Stryker now search for mutation within an expression that triggers an error whenever the original search method fails (mutation encompassing the faulty code).
Fixes #1533 and other SAFE mode errors.
> fix(rollback): rollback mutation in expressions that cause build error(s)

- src/Stryker.Core/Stryker.Core.UnitTest/Baseline/Providers/AzureFileShareBaselineProviderTests.cs
- src/Stryker.Core/Stryker.Core/Baseline/Providers/AzureFileShareBaselineProvider.cs
- src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs
> feat(baseline): Azure fileshare uses projectname as output path if specified

- .editorconfig
- src/Stryker.Core/Stryker.Core/Initialisation/CrossPlatformAssemblyResolver.cs
- src/Stryker.Core/Stryker.Core/Initialisation/CustomAssemblyResolver.cs
- src/Stryker.Core/Stryker.Core/Initialisation/EmbeddedResourcesGenerator.cs
Fix #1501 
Supersedes #1502 
@FrankvdStam I tested and cleaned up the PR. Looks good to me! I noticed you branched off of v1 but since this is a fix it can go straight to master. I created a new branch to fix this and cherry-picked your fixes onto it.
> fix: Improve reliability of embedded resources resolving

- docs/Configuration.md
- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/IgnoredMethodMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Options/StrykerOptionsTests.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/IgnoredMethodMutantFilter.cs
- src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs
Existing filters work as before: they only match against the method name. For example, the filter `Foo*` does not match the expression `Foo.Bar()`. However, a filter like `Foo.*`, `Bar`, or `Foo.Bar` will match that expression. Ignores comments and whitespace inside of the expression. Works for constructors too!
Resolves #1630
> Allow ignoring mutants of qualified method names

- docs/Configuration.md
I was going through the docs and couldn't run the command as is, so I updated it to match some of the other commands that pass in an array and thought I'd propose the change.
Thanks again for stryker!
> Update documentation to include wrapping quotes

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialisationProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectMutatorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/ProjectNameInputTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/ProjectVersionInputTests.cs
- src/Stryker.Core/Stryker.Core/Clients/DashboardClient.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InitialisationProcess.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs
- src/Stryker.Core/Stryker.Core/Options/Inputs/ProjectNameInput.cs
- src/Stryker.Core/Stryker.Core/Options/Inputs/ProjectVersionInput.cs
- src/Stryker.Core/Stryker.Core/Options/StrykerInputs.cs
- src/Stryker.Core/Stryker.Core/Reporters/DashboardReporter.cs
Thanks to [SourceLink][1], the repository URL and the full version (including the git SHA1) of a project can be included in the produced assembly.
This commit uses the information computed by SourceLink to automatically retrieve the project name (github.com/organization/project) and project version which are required for the dashboard reporter.
With this technique, the table on the [Stryker dashboard documentation][2] can be updated with ✅ everywhere for the Stryker.NET column since it doesn't depend on a specific CI provider to provide the repository URL and version.
Note that I have run `Stryker.CLI --reporter progress --reporter html --reporter dashboard` on my local checkout of https://github.com/0xced/serilog-formatting-log4net/tree/20e86d55b4bd9e3682c3608530398e794df12481 and it …
> feat(dashboard reporter): Retrieve the project name and version from the project under test using source link

- docs/configuration.md
- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFileTests.cs
- src/Stryker.CLI/Stryker.CLI.UnitTest/filled-stryker-config.json
- src/Stryker.CLI/Stryker.CLI/CommandLineConfigHandler.cs
- src/Stryker.CLI/Stryker.CLI/FileBasedInput.cs
- src/Stryker.CLI/Stryker.CLI/JsonConfigHandler.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/TestCaseFilterInputTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestRunnersTest.cs
- src/Stryker.Core/Stryker.Core/Options/Inputs/TestCaseFilterInput.cs
- src/Stryker.Core/Stryker.Core/Options/StrykerInputs.cs
- src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
Replaces #1557 and fixes #420.
- Added the option `--filter` to specify a [TestCaseFilter](https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests).
- Passed the option to VsTestRunner in two forms: one with the XML RunSettings and one as `TestPlatformOptions` parameter when calling `_vsTestConsole.RunTestsWithCustomTestHost()`. Previous work in #1557 had shown that both were required, since one is used during test discovery and the other is used during test execution.
- Tested the option with a very basic test of two xUnit tests. One test is attributed `[Trait("Category", "unit")]` and the other one `[Trait("Category", "integration")]`. When running Stryker.CLI without `--filter` option, the console outputs `Total number of tests found: 2.` with a correct HTML report. …
> feat(testrunner): Filter which unit tests are used during mutation test

- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/AccessorSyntaxOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/BlockOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/ExpressionSpecificOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/PostfixUnaryExpressionOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/StatementSpecificOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutationContext.cs
This is a small PR with some refactoring (mostly on MutationContext) to fix the orchestration classes design that were disrupted with the recent merge with `master`.
> Refactor v1.0 post merge

- src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
Before this commit:
```
$ dotnet stryker --verbose
Specify --help for a list of available options and commands.
Unhandled exception. McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized option '--verbose'
at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessUnexpectedArg(String argTypeName, String argValue)
at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] …
```
> feat: Show commandline hint when unrecognized option is used

- src/Stryker.Core/Stryker.Core/StrykerRunner.cs
It's simpler and the output is more readable thanks to the colors.
> chore: Use Serilog destructuring feature instead of serializing options as JSON

- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/StrykerVstestHostLauncher.cs
Once again, approval testing workflow (accepting changes by pasting what was put in the clipboard) doesn't mix well with mutation testing.
> Disable copying to clipboard when using Verify

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialisationProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectMutatorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core/Clients/DashboardClient.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InitialisationProcess.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs
- src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs
- src/Stryker.Core/Stryker.Core/Reporters/DashboardReporter.cs
- src/Stryker.Core/Stryker.Core/Reporters/JsonReporter/JsonReportFileComponent.cs
The automatic detection of project name and version introduced in https://github.com/stryker-mutator/stryker-net/pull/1663 broke the DashboardBaselineProvider because the project name would not be set and thus the report would be sent to an invalid URL: `/api/reports//version`
This commit addresses this issue by setting the project name and version on the StrykerOptions rather than on the DashboardClient and DashboardReporter (like it was originally done in https://github.com/stryker-mutator/stryker-net/pull/1532).
> fix: Dashboard baseline project name and version are not set

- src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/IgnoreMutationsInputTests.cs
- src/Stryker.Core/Stryker.Core/Mutators/Mutator.cs
Flip statement mutation to first in the enum so it will be picked first in case the statement mutator is chosen
closes #1762
> fix(Ignore mutations): Ignoring statement mutations is now possible

- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/BlockMutatorTests.cs
- src/Stryker.Core/Stryker.Core/Mutators/BlockMutator.cs
* Don't mutate empty blocks
* Don't mutate blocks in struct constructors containing assignments
* Don't mutate infinite while loops (thanks for the suggestion @Pentiva)
* Correctly deduce the first return-typed ancestor
* Only return `default` if the block contains a return statement
* Add tests
Only thing I'm not happy with is the struct constructor logic, which treats *any* assignment as a potential member assignment. Also, if some of the helper functions I wrote already exist, or should be elsewhere, please comment on that, I'm not too familiar with the code base.
Fixes issues (false positives) and warnings I faced while [updating my project to 1.0](https://github.com/sbergen/Responsible/runs/4059889905?check_suite_focus=true).
> fix(Block mutator): Prevent false positives from block mutations

- src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/CsharpMutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantPlacerTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutationSpecificSyntaxTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/BlockMutatorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestRunnersTest.cs
- src/Stryker.Core/Stryker.Core/Helpers/RoslynHelper.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InitialTestProcess.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/AnonymousFunctionExpressionToBodyEngine.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/EndingReturnEngine.cs
- src/Stryker.Core/Stryker.Core/Mutants/BaseMutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpMutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/AccessorSyntaxOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/AnonymousFunctionExpressionOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/BaseMethodDeclarationOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/NodeSpecificOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantPlacer.cs
- src/Stryker.Core/Stryker.Core/Mutators/BlockMutator.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
This PR brings a bunch of minor to medium fixes and improvements:
1. ignores any trailing spaces for `all` when disabling mutations via code comments (such as :`//Stryker disable all`), fixes #1781. Updated tests to add trailing whitespaces to prevent regression
2. fixes raised exception when there is no mutant to test. added a unit test to prevent regression. Fixes #1776 
3. add orchestrator for anonymous lambdas (and a return injection engine as well). This will reduce the risk of safe mode triggering on anonymous lambdas
4. refactored `BlockMutator`: `return` injection now (properly) relies on the orchestration logic; besides cleaning up the design, it removes some 'safe mode' triggers.Some helpers method have been moved to the `RoslynHelper` class.
5. improves the message when only …
> Fix disable all issue

- docs/configuration.md
- docs/migration-guide.md
- docs/reporters.md
- docs/stryker-in-pipeline.md
- src/Stryker.Core/Stryker.Core.UnitTest/Baseline/Providers/AzureFileShareBaselineProviderTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Baseline/Providers/DiskBaselineProviderTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/BaselineMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/DashboardMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/MutantFilterFactoryTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/FallbackVersionInputTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/ProjectVersionInputTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/SinceTargetInputTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Options/StrykerInputsTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/BaselineReporterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/ReporterFactoryTests.cs
- src/Stryker.Core/Stryker.Core/Baseline/Providers/AzureFileShareBaselineProvider.cs
- src/Stryker.Core/Stryker.Core/Baseline/Providers/DiskBaselineProvider.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/BaselineMutantFilter.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/MutantFilterFactory.cs
- src/Stryker.Core/Stryker.Core/Options/Inputs/FallbackVersionInput.cs
- src/Stryker.Core/Stryker.Core/Options/Inputs/ProjectVersionInput.cs
- src/Stryker.Core/Stryker.Core/Options/Inputs/SinceTargetInput.cs
- src/Stryker.Core/Stryker.Core/Options/StrykerInputs.cs
- src/Stryker.Core/Stryker.Core/Reporters/BaselineReporter.cs
- src/Stryker.Core/Stryker.Core/Reporters/ReporterFactory.cs
fix #1798
Technically this is a breaking change since I changed the folder paths but I don't think this will have a huge impact as it will simply mean regenerating the baseline once.
@richardwerkman do you agree with allowing this 'breaking' change in a fix?
@sbergen since you actually use this feature, do you agree with changing the folder path from `dashboard-compare` to `baseline`?
> fix(baseline): Use regular fallback version as well as baseline fallback version

- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/IgnoredMethodMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/CsharpMutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/BlockMutatorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Progress/ProgressBarReporterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
- src/Stryker.Core/Stryker.Core/Helpers/RoslynHelper.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/AnonymousFunctionExpressionToBodyEngine.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/EndingReturnEngine.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/IgnoredMethodMutantFilter.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutantPlacer.cs
- src/Stryker.Core/Stryker.Core/Mutators/BlockMutator.cs
- src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressBar.cs
1. Block and statement mutations may now be ignored by IgnoredMethod option. Technically, statement mutations are ignored if the original code is an invocation of an 'ignored' method; block mutations are ignored if they only contain invocations of ignored method (or blocks of).
2. Fix exceptions when rolling back some expression body to statement body conversion. Technically, mutations are (now) rolled back with a depth first approach
3. Fix breaking `return default;` added to anonymous lambda that do not return any value. Technically, there is now a check to verify if the lambda contains a `return xxx` statement.-; if not, the lambda is assumed as `void`. This removes all related compilation errors but it should not have any impact on overall result.
4. Fix compilation errors with switch …
> Miscellaneous fixes and improvments

- src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs
> fix(initialisation): Make sure to select valid IAnalyzerResult from Buildalyzer

- src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
- src/Stryker.CLI/Stryker.CLI/packages.lock.json
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialisationProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InputFileResolverTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/TargetFrameworkResolutionTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestRunnersTest.cs
- src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
- src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InitialisationProcess.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectInfo.cs
- src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
- src/Stryker.Core/Stryker.Core/packages.lock.json
This is safer to use than a hand-rolled version. The public methods and the public `Framework` enum have been marked obsolete.
> Use the NuGet.Frameworks package to parse target frameworks

- src/Stryker.CLI/Stryker.CLI/CommandLineConfig/CommandLineConfigHandler.cs
As per [this](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefcommit-ishacommit-ishalsocommittish). Sorry I'm meticulous.
> docs: Fix typo in committish

- src/Stryker.Core/Stryker.Core/Options/Inputs/ConcurrencyInput.cs
Should fix #1927
I have seen reports online about the method also reporting `-1`, so wanted to be safe and did check on any value lower then `1`.
Added a warning and a message that the user can get rid of the warning by supplying a value themselves, they probably know the amount of processors that would make sense.
Can't think of an easy way of adding unit test coverage for this.
> Guard against `ProcessorCount` reporting values lower then `1`

- src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
- src/Stryker.CLI/Stryker.CLI/packages.lock.json
- src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
- src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
- src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
This reverts commit e7427cee807df53388e6b009052b35b6a76881cf.
Fix #1948
> fix(regex mutations): Revert inclusion of referenced projects because transitive dependencies are not included

- src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
- src/Stryker.CLI/Stryker.CLI/Clients/StrykerNugetFeedClient.cs
- src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
- src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
- src/Stryker.CLI/Stryker.CLI/packages.lock.json
- Only check for a preview release if a stable release is _not_ available in order to avoid having two messages inviting to upgrade to two different versions of Stryker.NET
- Actually check for a preview release instead of just the last release (versions.Max() would get the last release)
Also, use the `NuGet.Protocol` package to retrieve the list of versions so that Stryker.NET can benefit from the global NuGet caching mechanism.
> fix: Version update check at startup no longer recommends upgrading to preview and latest

- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/ExcludeFromCodeCoverageFilterTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/ExcludeFromCodeCoverageFilter.cs
Fix ExcludeFromCodeCoverageFilter not ignoring code when a reason is used: #1963
Removes spurious logs: #1957
> fix(filters): ExcludeFromCodeCoverage not working when justification is given

- src/Stryker.Core/Stryker.Core/MutantFilters/BaselineMutantFilter.cs
Since the `matchingMutants` is an IEnumerable<Mutant> it will be evaluated twice. But the `ResultStatus` is changed between the two calls to `First()` making it possible that the second evaluation returns no matches.
Full stack trace:
```
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
at System.Linq.ThrowHelper.ThrowNoElementsException()
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
at Stryker.Core.MutantFilters.BaselineMutantFilter.SetMutantStatusToBaselineMutantStatus(JsonMutant baselineMutant, IEnumerable`1 matchingMutants)
at Stryker.Core.MutantFilters.BaselineMutantFilter.UpdateMutantsWithBaselineStatus(IEnumerable`1 mutants, IReadOnlyFileLeaf file)
at Stryker.Core.MutantFilters.BaselineMutantFilter.FilterMutants(IEnumerable`1 …
```
> fix(baseline): potential InvalidOperationException: Sequence contains no elements

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/CsharpMutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/AnonymousFunctionExpressionToBodyEngine.cs
- src/Stryker.Core/Stryker.Core/Instrumentation/LocalFunctionExpressionToBodyEngine.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/AnonymousFunctionExpressionOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/BaseMethodDeclarationOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/LocalFunctionStatementOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutationStore.cs
Prevent migration of mutations from a method to a locally defined function as those lead to errors. 
Significant rewrite for 'LocalFunctionStatementOrchestrator' and 'AnonymousFunctionExpressionOrchestrator'.
Isolated the migration of the expression body (if present) to ensure a proper handling of the mutation context which prevents mutation migrating to other places.
Should also resolve some compile error mutant (see `CsharpMutantOrchestratorTests`: previous version of the test shows that the generated code will not compile)
Fix #1986
> fix(mutating): Better support for mutating local function

- docs/technical-reference/testing-framework.md
- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestRunnersTest.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestDescription.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
Stryker no longer aggregates test duration when multiple test results are provided for the same test case. 
Fix #2002
> fix(testrunner): Properly handle execution time for xUnit theories

- src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/IgnoreMutationsInputTests.cs
- src/Stryker.Core/Stryker.Core/Options/Inputs/IgnoreMutationsInput.cs
Support internal name  on top of description. More specifically accept `Regex` as a valid value.
fix #2001
> fix(ignore-mutations): Support mutator names as well as descriptions

- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestDescription.cs
Fix exception for duplicated XUnit tests, which are not executed.
#2016
> Add default duration for not executed duplicated xunit tests

- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigReaderTests.cs
- src/Stryker.CLI/Stryker.CLI/CommandLineConfig/CommandLineConfigHandler.cs
- src/Stryker.CLI/Stryker.CLI/ConfigReader.cs
To fix this issue, I thought that an InputException should only be thrown if the invalid config was provided by the user.
If no config is provided and the default config is not present, do as before and silently continue.
Note: This is my first PR for the Stryker project, do not hesitate to suggest changes.
> fix(options): Stryker silently runs with default config if custom config file is set but not found

- docs/configuration.md
It seems that it's no longer `azure-storage-sas` but now `azure-fileshare-sas`.
Updating the docs to reflect this.
> docs: Update the reference for the azure-storage-sas

- src/Stryker.Core/Stryker.Core/Baseline/Providers/AzureFileShareBaselineProvider.cs
… Signed Version Compatibility
Removed a set of Headers that were beeing appended to http requests when using AzureFileShare as a
provider for Baseline. The headers `x-ms-file-permission`, `x-ms-file-attributes`,
`x-ms-file-creation-time` and `x-ms-file-last-write-time` are now deemed to be optional, and as a
result can be removed. By removing these headers, we are allowing ourselves to be able to use SAS
tokens that have been generated with a Signed Version that is lower than `2019-02-02`.
fix #2114
> fix(baseline): increase compatibility of azure file share provider with older SAS keys

- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestRunnerPoolTests.cs
- src/Stryker.Core/Stryker.Core/CoverageAnalysis/CoverageAnalyser.cs
Test runners and coverage analyzers refactoring introduced a regression in V2.1: mutations in field initializers where no longer flagged as needing full testing; this lead to some false survivors (see #2118).
This PR fixes that and add a regression test
> Fix: static mutants not marked as needing all tests

- src/Stryker.Core/Stryker.Core/Exceptions/GeneralStrykerException.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestContextInformation.cs
> fix(exception logging): Log vstest exceptions instead of swallowing

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialisationProcessTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InitialisationProcess.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectInfo.cs
Implements #2126:
when no tests are detected Stryker verifies if there is a test runner present for each tes framework and stops on exception otherwise.
Limit: this only triggers if no test is detected in any test projects (if more than one is present).
_Note: the implementation is in a dedicated method and be run at another point in time if need arises._
> feat(testrunner): Diagnose failed test discovery and provide fix hints

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestExecutorTests.cs
- src/Stryker.Core/Stryker.Core/Mutants/Mutant.cs
- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestExecutor.cs
- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs
- src/Stryker.Core/Stryker.Core/TestRunners/CoverageRunResult.cs
I found circumstances where Stryker does not properly marks TimedOut mutants (while working on diagnose mode).
This PR fixes this issue.
Note: current design for TimeOut handling is insufficiently cohesive. This comes from the fact that Stryker must handle situations where it cannot identify which test timed out, which happens when this is the very first test to be executed by VsTest (apparently).
An improved refactoring will be provided with diagnose mode. I made this call to avoid a complex merge in the coming weeks 😄 .
> fix: Stryker not properly flagging mutant as TimedOut

- src/Stryker.Core/Stryker.Core/libman.json
Fixes theme color for Ignored mutants.
Hides unnecessary mutant id from mutant drawer.
> deps(html report): Update mutation-testing-elements to 1.7.11

- docs/configuration.md
- src/Stryker.Core/Stryker.Core.UnitTest/Baseline/Providers/AzureFileShareBaselineProviderTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/AzureFileStorageSasInputTests.cs
- src/Stryker.Core/Stryker.Core/Baseline/Providers/AzureFileShareBaselineProvider.cs
- src/Stryker.Core/Stryker.Core/Options/Inputs/AzureFileStorageSasInput.cs
This PR stops Stryker from making the assumption that the SAS Token is in a specific format.
It will now take the SAS token that has been provided, do some basic validation to ensure that it has the correct parameters (SV & Sig) and will then pass it along to the file share operations.
One thing to note, the order of the query parameters has changed, but the outcome is still the same.
Fixes #2148
> fix(azure-baseline): Use full SAS token format instead of making assumptions and transformations on the token

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectMutatorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestMockingHelper.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InitialisationProcess.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/FilePatternMutantFilter.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/MutantFilterFactory.cs
- src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs
- src/Stryker.Core/Stryker.Core/MutationTest/FsharpMutationProcess.cs
- src/Stryker.Core/Stryker.Core/MutationTest/IMutationProcess.cs
- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs
- src/Stryker.DataCollector/Stryker.DataCollector/CoverageCollector.cs
Refactor process classes to simplify design. Get rid of some intermediate factory classes.
Reduce coupling with C# and F# coupling, giving the opportunity to move the incomplete F# support to a dedicated project, or at least branch
> chore: Refactor dependency injection

- src/Stryker.Core/Stryker.Core.UnitTest/Compiling/RollbackProcessTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
Ensure Stryker identifies properly Constructor as an appropriate scope for safe mode.
Ensure Stryker rolls back every mutation in the concerned source file when it fails to find the error enclosing scope. Previous versions of Stryker used the offending syntax node as the scope, leading to internal compilation errors when triggered.
Note that I have not been able to devise a unit test for that, as I did not find any way to trigger this condition with correct code.
The alternative to this could be to raise an exception when no scope is found, but it means blocking users when this happens.
> Safe mode now works properly in constructors

- src/Stryker.Core/Stryker.Core.UnitTest/DiffProviders/GitDiffProviderTests.cs
- src/Stryker.Core/Stryker.Core/DiffProviders/GitDiffProvider.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/SinceMutantFilter.cs
Correct the classification of changed files in GIT as source or test files in `GitDiffProvider` when using the `SinceMutantFilter`.
fix #2255 
Also correct the displayed number of total changed files in the Log when using the `SinceMutantFilter`.
> fix(since): correctly classify changed files as source or test files

- src/Stryker.Core/Stryker.Core/CoverageAnalysis/CoverageAnalyser.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
fix #2251, workaround a potential bug in some xUnit versions
> Use null instead of empty string for TestCaseFilter parameter

- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/HtmlReporterTests.cs
- src/Stryker.Core/Stryker.Core/Reporters/HtmlReporter/HtmlReporter.cs
> fix(reporting): Spaces in the output path are supported for the -o option

- CONTRIBUTING.md
In the CONTRIBUTING.MD, there are instructions for running Stryker locally. I added a reference to the existing integration test projects so that people don't need to setup their own dummy project.
> docs: add reference to integration test projects in contribution guide

- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/AssignmentStatementMutatorTests.cs
- src/Stryker.Core/Stryker.Core/Mutators/AssignmentStatementMutator.cs
Fixed that the output of the AssignmentMutator is missing a space after the operator.
> fix(assignment statement mutator): Add trivia between operands

- src/Stryker.Core/Stryker.Core/Reporters/Json/SourceFiles/JsonMutant.cs
Now using `SyntaxNode.ToString()` instead of `SyntaxNode.ToFullString()` in the `JsonMutant` class. [`SyntaxNode.ToFullString()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.syntaxnode.tofullstring?view=roslyn-dotnet-4.3.0) also includes leading and trailing trivia. Leading trivia should not be necessary as the location is already set here:
https://github.com/stryker-mutator/stryker-net/blob/085a0b7837370b709b00285ba4efe5ad55718a0a/src/Stryker.Core/Stryker.Core/Reporters/Json/SourceFiles/JsonMutant.cs#L35
This change renders the report correctly: 
Q: Should trailing trivia be included?
Fixes #2270
> fix(reporting): Correctly show whitespace in report

- src/Stryker.Core/Stryker.Core/Mutators/InitializerMutator.cs
Based on [this](https://github.com/stryker-mutator/stryker-net/pull/2259#discussion_r1009704958) comment.
> chore: initializermutator expressions cannot be less than 0

- docs/operating-modes.md
Added a new page to the documentation to specify the different ways to run Stryker. I did not document the solution context way, as it's still in progress (right?).
Closes #2281
> docs(operating modes): Add operating modes page

- src/Stryker.Core/Stryker.Core.UnitTest/Fsharp/FsharpFileDetectionTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialBuildProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InputFileResolverTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/NugetRestoreProcessTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs
- src/Stryker.Core/Stryker.Core/Initialisation/NugetRestoreProcess.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs
- src/Stryker.Core/Stryker.Core/ToolHelpers/MsBuildHelper.cs
Code to implement feature request https://github.com/stryker-mutator/stryker-net/issues/2356 (When setting the --msbuildPath option, the nuget restore should also use this msbuild to restore all the nuget packages)
Added 2 commits, 
one to implement the use of the msbuildPath cli option for the nuget restore 
the other one to change the default return of the MsBuildHelper to first look for the highest version of Visual Studio, only then trying to give Visual Studio 2017 Enterprise MsBuild path .
> feat(nugetrestore): use MsBuild option during nuget restore

- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/NullCoalescingExpressionMutatorTests.cs
- src/Stryker.Core/Stryker.Core/Mutators/NullCoalescingExpressionMutator.cs
As discussed in the linked issue, certain mutations from `NullCoalescingExpressionMutator` will generate invalid code if the right hand side of the expression is a `throw`.
These are simple to filter out by checking if `node.Right` is of type `SyntaxKind.ThrowExpression`.
Fixed #2387
> fix(NullCoalescingExpressionMutator): Don't generate certain mutants when right hand side is ThrowExpression (#2387)

- docs/configuration.md
- src/Stryker.CLI/Stryker.CLI.UnitTest/FileConfigReaderTests.cs
- src/Stryker.CLI/Stryker.CLI.UnitTest/filled-stryker-config.json
- src/Stryker.CLI/Stryker.CLI.UnitTest/filled-stryker-config.yaml
- src/Stryker.CLI/Stryker.CLI/FileBasedInput.cs
- src/Stryker.CLI/Stryker.CLI/FileConfigReader.cs
As per discussion here: https://github.com/stryker-mutator/stryker-net/pull/2151#issuecomment-1406919865
This PR basically borrows from the initial commits in the PR above. I also tested this manually.
> Adding break-on-initial-test-failure option to the config file

- src/Stryker.Core/Stryker.Core.UnitTest/Options/StrykerOptionsTests.cs
- src/Stryker.Core/Stryker.Core/Clients/DashboardClient.cs
- src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs
Pull request #2055 (fix(Reporting): Fix issue with relative paths that miss the root folder) broke pull request #1710 (fix: Dashboard baseline project name and version are not set).
I have added a new test to ensure that this does not regress in the future.
Before this commit, an HTTP 404 error would occur because the dashboard URL was not correct:
```
[12:46:37 ERR] Failed to upload report to the dashboard
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
at Stryker.Core.Clients.DashboardClient.PublishReport(JsonReport report, String version)
[12:46:37 ERR] Uploading to stryker dashboard failed...
```
> fix(dashboard reporter): fix dashboard publishing when the project name is computed

- src/Stryker.Core/Stryker.Core/Reporters/DashboardReporter.cs
- src/Stryker.Core/Stryker.Core/Reporters/HtmlReporter/HtmlReporter.cs
- src/Stryker.Core/Stryker.Core/Reporters/Json/JsonReporter.cs
Also simplify writing text with Spectre.Console by using the WriteLine method directly with a style. This avoids unnecessary markup parsing.
> fix(dashboard reporter): Actually print the hint in cyan

- docs/configuration.md
- src/Stryker.CLI/Stryker.CLI.UnitTest/StrykerCLITests.cs
- src/Stryker.CLI/Stryker.CLI/CommandLineConfig/CommandLineConfigReader.cs
So this adds an option to specify TFM in the command line in addition to the config file.
Some context: in our repo, we are now changing the way we execute mutation testing. Instead of having one TFM value in the config and hoping that random selection works wherever this TFM is not available, we are going to have the information about the desired TFM elsewhere and use it when running Stryker for every particular project. 
This will save some time and make mutation testing results more deterministic.
I checked this manually for a little repro also :)
> Adding TFM command line option

- src/Stryker.Core/Stryker.Core/Reporters/Json/JsonReport.cs
- src/Stryker.Core/Stryker.Core/Reporters/Json/SourceFiles/SourceFile.cs
- src/Stryker.Core/Stryker.Core/Reporters/Json/TestFiles/JsonTestFile.cs
> fix(baseline): json reports with testfiles are now correctly deserialized

- src/Stryker.Core/Stryker.Core.UnitTest/ProjectComponents/TestProjects/TestProjectTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
- src/Stryker.Core/Stryker.Core.UnitTest/TestHelper.cs
- src/Stryker.Core/Stryker.Core.UnitTest/TestResources/ExampleTestFilePreprocessorSymbols.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs
- src/Stryker.Core/Stryker.Core/ProjectComponents/TestProjects/TestProject.cs
> fix(tests report): Correctly parse test files with preprocessor symbols

- azure-pipelines.yml
- docs/getting-started.md
- integrationtest/IntegrationTest.sln
- integrationtest/TargetProjects/EmptyTestProject/EmptyTestProject.csproj
- integrationtest/TargetProjects/EmptyTestProject/UnitTest.cs
- integrationtest/TargetProjects/EmptyTestProject/Usings.cs
- integrationtest/TargetProjects/EmptyTestProject/packages.lock.json
- integrationtest/TargetProjects/IntegrationTestApp.sln
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialTestProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Html/Realtime/SseServerTest.cs
- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestMockingHelper.cs
- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestRunnerPoolTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTextContextInformationTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InitialTestProcess.cs
- src/Stryker.Core/Stryker.Core/Initialisation/TimeoutValueCalculator.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/RunEventHandler.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/StrykerVstestHostLauncher.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestContextInformation.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
Fix issue #2549 : Stryker now warns when no test are present.
Fix issue #2559 : Stryker now disables parallelism for MsTest
Also implement a revised strategy for handling hanged VsTest:
1. For initial test session: wait for VsTest to stop, then wait for the end notification (if not received yet). No failover available for the time being.
2. For other test sessions: 
1. wait for the end notification: if it times out, this session is discarded
2. then, wait for the end of the session: if it times out, we assume VsTest hanged during clean up phase, it will be recycled, but the session is discarded.
1. if anything timed out, VsTest console is recycled
1. if the test session is discarded, a new attempt is made
1. an exception is thrown after 5 failed attempts
> fix(testrunner): fix scenario where vstest would hang if no tests were detected

- src/Stryker.Core/Stryker.Core.UnitTest/Clients/DashboardClientsTest.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/BaselineMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Json/JsonReporterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Json/MockJsonReport.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Json/MockJsonReportFileComponent.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/ReportTestHelper.cs
- src/Stryker.Core/Stryker.Core/Reporters/Json/JsonReport.cs
> fix(report): Use fullPath for file name in json and html report

- azure-pipelines.yml
Since it's not being tested anyway
> ci: Stop publishing Stryker.Core for integration test

- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestMockingHelper.cs
- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestRunnerPoolTests.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
Testing on project shows that current timeout value before assuming VsTest is frozen is too aggressive, triggering unneeded retries.
This PR increase this value from 3 seconds to 10.
> fix: Increase time out before assuming VsTest is frozen

- CONTRIBUTING.md
There is a small glitch in the steps described to run Stryker.NET on a local project.
The Stryker.CLI.sln file is mentioned but it's actually Stryker.sln that should be used.
> doc(contributing): fixes solution file name 

- src/Stryker.Core/Stryker.Core.UnitTest/ProjectComponents/SourceProjects/SourceProjectInfoTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/ProjectComponents/TestProjects/TestProjectsInfoTests.cs
So flaky that I can reproduce :D 
https://github.com/stryker-mutator/stryker-net/assets/5451366/c2fdba0f-9157-410d-9061-06ee3831bbb3
I guess due to some object allocation reasons, the logger factory usually happens to be initialized for the TestProjectInfoTests, but looks like the common way to do it here is to inherit `TestBase` which does this in the ctor.
> chore: Fix flaky test

- azure-pipelines.yml
- integrationtest/IntegrationTest.sln
- integrationtest/TargetProjects/Library.FSharp.XUnit/Library.FSharp.XUnit.fsproj
- integrationtest/TargetProjects/Library.FSharp.XUnit/LibraryTests.fs
- integrationtest/TargetProjects/Library.FSharp.XUnit/packages.lock.json
- integrationtest/TargetProjects/Library.FSharp.XUnit/stryker-config.json
- integrationtest/TargetProjects/Library.FSharp/Library.FSharp.fsproj
- integrationtest/TargetProjects/Library.FSharp/Library.fs
- integrationtest/TargetProjects/Library.FSharp/packages.lock.json
- integrationtest/ValidationProject/ValidateStrykerResults.cs
- src/Stryker.Core/Stryker.Core/Compiling/FsharpCompilingProcess.cs
- src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs
- This fixes a hard crash happening currently for F# projects and adds an integration test to keep an eye on that.
- The integration test basically just verifies no crash and only runs on Ubuntu to save the pipeline resources.
- Also, a couple of small things
> chore: An integration test for F#

- README.md
due to case sensitivity of stryker-mutator.io
With uppercase first letter (before this change) the browser briefly shows a "page not found" before loading the correct page.
Some browsers (like mine) will keep showing a "do you want to check if a saved version .." at the top of the page.
> docs(readme): link lower case

- src/Stryker.Core/Stryker.Core/ProjectComponents/TestProjects/TestProjectsInfo.cs
This is a workaround for a relatively common issue where test assemblies are still in use by Windows Error Reporting (most likely) if there are crashes (e.g., stack overflows). It can be really painful when at the end of a long test run this happens and all results are just thrown away.
```
Unhandled exception. System.IO.IOException: The process cannot access the file 'C:\_work\1\s\artifacts\bin\Stryker\nnnn\net7.0\nnnn.dll' because it is being used by another process.
at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
at System.IO.Abstractions.FileWrapper.Copy(String sourceFileName, String destFileName, Boolean overwrite)
at Stryker.Core.ProjectComponents.TestProjects.TestProjectsInfo.RestoreOriginalAssembly(IAnalyzerResult sourceProject) in …
```
> fix: Don't fail the test run if restoring test assemblies fails

- src/Stryker.Core/Stryker.Core.UnitTest/Helpers/RangeHelperTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Helpers/TextSpanHelperTests.cs
- src/Stryker.Core/Stryker.Core/FilePattern.cs
- src/Stryker.Core/Stryker.Core/Helpers/RangeHelper.cs
- src/Stryker.Core/Stryker.Core/Helpers/TextSpanHelper.cs
- src/Stryker.Core/Stryker.Core/ProjectComponents/ProjectComponentsExtensions.cs
Part of [this PR](https://github.com/stryker-mutator/stryker-net/pull/2645).
This adds some F# range arithmetic which is needed for comparing mutant spans.
Now, the F# part is basically reimplemented C# `TextSpan` math. There are common parts and we technically could extract some common code, but my experimentation showed it's not going to be better. The reasons are:
- there are already too many abstraction in the Stryker code base and my brain hurts
- F# `range` type is filepath-aware so range construction would look different and would require some wrappers
- range math, like any math, is not really a subject to change, and we're not expecting other lang-specific impls either
> chore: F# range math

- src/Stryker.Core/Stryker.Core/Initialisation/FsharpProjectComponentsBuilder.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs
Part of [this PR](https://github.com/stryker-mutator/stryker-net/pull/2645).
This is just aligning the code flow with C#. Options will be of use.
> chore: Passing Stryker options to F# project components

- src/Stryker.Core/Stryker.Core.UnitTest/Helpers/RangeHelperTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs
- src/Stryker.Core/Stryker.Core/Helpers/RangeHelper.cs
- src/Stryker.Core/Stryker.Core/Helpers/TextSpanHelper.cs
Fix various sonar issues
Complete TODO to make indexing methods work cross-platform
> chore: Code quality improvements

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialBuildProcessTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InitialBuildProcess.cs
Add a retry logic for initial build. If a solution fails to build with `dotnet build`, Stryker simply retries with `MsBuild` instead.
Fixes #2668 
EDIT: I did some manual testing of this by adding a SQL project to some netcore project: it fails without the fix and succeed with.
> feat: Retry build with msbuild when dotnet build fails

- src/Stryker.Core/Stryker.Core.UnitTest/Options/StrykerInputsTests.cs
- src/Stryker.Core/Stryker.Core/Options/Inputs/SinceInput.cs
> fix: Validation on Since enablement when Baseline is also enabled

- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Html/HtmlReporterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Html/RealTime/Events/SseEventTest.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Html/RealTime/Events/SseEventTypeTest.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Html/RealTime/RealTimeMutantHandlerTest.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Html/RealTime/SseServerTest.cs
- src/Stryker.Core/Stryker.Core/Reporters/Html/HtmlReporter.cs
- src/Stryker.Core/Stryker.Core/Reporters/Html/RealTime/Events/SseEvent.cs
- src/Stryker.Core/Stryker.Core/Reporters/Html/RealTime/Events/SseEventType.cs
- src/Stryker.Core/Stryker.Core/Reporters/Html/RealTime/IRealTimeMutantHandler.cs
- src/Stryker.Core/Stryker.Core/Reporters/Html/RealTime/ISseServer.cs
- src/Stryker.Core/Stryker.Core/Reporters/Html/RealTime/RealTimeMutantHandler.cs
- src/Stryker.Core/Stryker.Core/Reporters/Html/RealTime/SseServer.cs
Mostly `Realtime` -> `RealTime` for namespaces and filenames.
> fix(real-time): naming inconsistencies

- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigBuilderTests.cs
- src/Stryker.CLI/Stryker.CLI/FileConfigReader.cs
> fix(file config): Since and Baseline are implicitly enabled when the config object exists in the config file

- src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs
Just like #1900 but for the InputFileResolver.
This was not an issue until https://github.com/daveaglick/Buildalyzer/pull/198 was reverted in https://github.com/daveaglick/Buildalyzer/commit/8e85a15e324a65f9da5033f3d8a2320c76dda378 for the Buildalyzer 6.0.1 release. Before this change in Buildalyzer, the empty target framework was sorted last but since v6.0.1 it's sorted first instead.
Also, improve the NotSupportedException message when the language is undefined because `System.NotSupportedException: Specified method is not supported` is a terrible message.
> fix: Make sure to select valid IAnalyzerResult from Buildalyzer

- CONTRIBUTING.md
Existing instruction does not work (I assume the argument have been deprecated and removed).
Possibly this should be expanded with one more change as the instruction in `CONTRIBUTING.md` is similar to, but different from this:
https://github.com/stryker-mutator/stryker-net/blob/70adc60caad193ed6942ee970ea5373003ade4e4/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L13-L13
> docs(contributing): Update debug log instruction

- docs/technical-reference/VsTest internal.md
This PR describes a workaround for OpenSSL to the "Known Issues" section which might happen on operating systems with newer OpenSSL implementations. 
https://github.com/stryker-mutator/stryker-net/issues/2799#issuecomment-1868758607
> docs: add openssl workaround to 'known issues'

- adding_a_mutator.md
The doc mentioned that Stryker.NET does not support semantic model, but this had been changed.
> docs(adding_a_mutator): remove incorrect fact about semantic model support

- .github/release.yml
- .github/workflows/integration-test.yaml
> ci: Add m1 macos integration test with github actions

- src/Stryker.Core/Stryker.Core/libman.json
Includes plenty of fixes and improvements, so we should use this in Stryker.NET.
https://github.com/stryker-mutator/mutation-testing-elements/compare/v2.0.3...v3.0.2
> deps(reporting): update mutation-testing-elements to `3.0.2`

- src/Stryker.Core/Stryker.Core.UnitTest/InjectedHelpers/InjectedHelperTests.cs
- src/Stryker.Core/Stryker.Core/InjectedHelpers/MutantControl.cs
Ensure MutationControl class, which is injected into mutated code, compiles without warnings with 'nullable' option on while remaining compatible with C# 2
Fix issue #2867
> fix: Ensure MutationControl compiles with 'nullable' enabled

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/CsharpMutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core/Compiling/CSharpRollbackProcess.cs
- src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs
- src/Stryker.Core/Stryker.Core/Initialisation/EmbeddedResourcesGenerator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpMutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/ConditionalExpressionOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/ExpressionBodiedPropertyOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/InvocationExpressionOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/MemberAccessExpressionOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/NodeSpecificOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutationContext.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutationStore.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunnerPool.cs
- src/Stryker.DataCollector/Stryker.DataCollector/CoverageCollector.cs
Fix issues related to Conditional Access (and NullSuppression operator)
Add recovery mechanism for when the compilation triggers null reference exception
Fix #2880
> fix: Conditional access mutations could lead to unrecoverable NullReferenceException in compilation

- src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs
Stryker can now ignore some error reported by code generators. It may still fail when code generators are actually needed, but project not using those will no longer be affected.
Fix #2881.
May also fix #2736, #2776, #2797 and #1486
~~Note: a proper fix requires to find an instance of [AnalyzerConfigOptionsProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.analyzerconfigoptionsprovider?view=roslyn-dotnet-4.7.0) or implement one, which seems non trivial in the general sense. But a basic implementation returning values from `IAnalyzerResult` properties may be sufficient for some or most use cases.~~
It turns out that implementing the basic version of an `AnalyzerConfigOptionsProvider` was straightforward and it fixes this issue. It should also help …
> fix: Forward build options to code analyzers and generators

- src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs
> fix: Use ConcurrentBag instead of List to prevent InvalidOperationException during mutation

- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/IgnoredMethodMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/IgnoreMethodsInputTests.cs
- src/Stryker.Core/Stryker.Core/Options/Inputs/IgnoreMethodsInput.cs
Ensure (explicit) generic method calls (such as `ToList<int>()`) are supported by the `IgnoreMethodFilter`.
To be more specific, type specifications are simply ignored: `ToList<int>()` is dealt with as if it was simply `ToList()`.
> fix: support generic method calls for ignoremethodfilter

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/CsharpMutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/BaseFunctionOrchestrator.cs
Parameterless delegates returns a null parameter block, which is now properly handled
fixes #2925.
> Fix: NullReferenceException when mutating parameterless delegates

- LICENSE
Copyright appendix is meant to add as a header to source files, it is not meant to be in the LICENSE file.
> chore: Remove copyright appending from LICENSE

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/CsharpMutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTestsBase.cs
- src/Stryker.Core/Stryker.Core/Mutants/BaseMutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpMutantOrchestrator.cs
Previously the mutation testrun in solution mode would produce non-unique mutant ids, which resulted in incorrect mutant updates in the real-time report.
By making this value static, it works correctly again.
> fix(real-time-reporting): missing mutants when running in solution mode

- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigBuilderTests.cs
- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFiles/MultipleDefaultWithJson/stryker-config.json
- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFiles/MultipleDefaultWithJson/stryker-config.yaml
- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFiles/MultipleDefaultWithJson/stryker-config.yml
- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFiles/SingleDefaultYaml/stryker-config.yaml
- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFiles/SingleDefaultYml/stryker-config.yml
- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFiles/TwoWithYml/stryker-config.yaml
- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFiles/TwoWithYml/stryker-config.yml
- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFiles/UserConfigWithDefault/custom_config.json
- src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFiles/UserConfigWithDefault/stryker-config.json
- src/Stryker.CLI/Stryker.CLI.UnitTest/Stryker.CLI.UnitTest.csproj
- src/Stryker.CLI/Stryker.CLI/ConfigBuilder.cs
Fixes #2830 
This PR adds support for parsing "stryker-config.yml" and "stryker-config.yaml" as default configuration files.
Eliminates the need to pass those files in each time.
Needed to add the "Collection" attribute to some tests so that they don't run in parallel and affect each other by setting/getting the default directory.
> feat: Parse stryker-config.yml and stryker-config.yaml by default

- src/Stryker.CLI/Stryker.CLI.UnitTest/StrykerCLITests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Html/RealTime/SseServerTest.cs
- src/Stryker.Core/Stryker.Core/Reporters/Html/RealTime/SseServer.cs
> fix(real-time-reporting): Properly handle when browser is closed during mutation testing

- integrationtest/TargetProjects/NetCore/NetCoreTestProject.NUnit/Constructs.cs
- integrationtest/TargetProjects/NetCore/NetCoreTestProject.XUnit/VariousTests.cs
- integrationtest/TargetProjects/NetCore/TargetProject/StrykerFeatures/UseAssert.cs
- integrationtest/Validation/ValidationProject/ValidateStrykerResults.cs
- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/CoverageCollectorTests.cs
- src/Stryker.DataCollector/Stryker.DataCollector/CoverageCollector.cs
Make Stryker compatible with debug assertions logic, so that a mutant is considered as killed if it result in a failed assertion.
Disable `Debug.Assert` report dialogs. Failed assertions result in an argument exception raised, ensuring this are recognized as failed tests by Stryker.
Fixes #2375
Note: coverage reporting is wrong. For some reason, Sonar does not capture any coverage data for the DataCollector. I have added a dedicated test that does cover all testable lines.
> fix: Disable debug trace

- integrationtest/Validation/ValidationProject/ValidateStrykerResults.cs
- src/Stryker.CLI/Stryker.CLI.UnitTest/StrykerCLITests.cs
- src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/BaselineMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/ExcludeMutationMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/FilePatternMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/IgnoreBlockMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/IgnoredMethodMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/SinceMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/CsharpMutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTestsBase.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs
- src/Stryker.Core/Stryker.Core/Mutants/BaseMutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpMutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/ConstantPatternSyntaxOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/IdProvider.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutationContext.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutationStore.cs
- src/Stryker.Core/Stryker.Core/MutationTest/MutationTestExecutor.cs
- src/Stryker.Core/Stryker.Core/Mutators/StringMutator.cs
- src/Stryker.Core/Stryker.Core/Options/StrykerInputs.cs
- src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs
Main (unique?) visible impact is the ability to mutate strings that are part of case in switch expressions.
Note that this allows new mutators (that remain to be defined as of today).
Fix #2951
Not related: 
- Wrap Spectre Console for usage with CommandLineUtils. This increase overall consistency and fixes a flaky test.
- Mutant IDs generation is in a dedicated component
- Restore stable and known mutant IDs for unit tests
> feat(mutating): constant patterns

- docs/ignore-mutations.md
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/CsharpMutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTestsBase.cs
- src/Stryker.Core/Stryker.Core/Helpers/RoslynHelper.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/BlockOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/CommentParser.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/NodeSpecificOrchestrator.cs
Add support for the so called multiline comments format (`/* comment */ `) for Stryker comments.
Updated the doc and provided some detailed explanation for `once` option. Note that the Stryker comment must still be on a single line.
Multiline comments should work exactly line single line comments when put on a dedicated line.
Stryker attempts to associate comments within the line with the **previous** syntax node, that is:
`if (condition) {/* Stryker comment*/;....}`: this comment will apply to the whole syntax block
`if (/* Stryker comment*/ condition) {....}`: this comment will apply to the whole condition expression
Stryker comments may not be detected if they are within a syntax node
`if (cond/* Stryker comment*/ition) {....}`: will have no effect
`if (condition /* Stryker comment*/) …
> feat(ignore mutation): Add support for ignoring mutations in code using mutiline string comments

- src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestRunnerPoolTests.cs
- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
Log when Vstest failed three times in a row instead of aborting the run. The run will be handled as a regular timeout instead.
The mutation test phase is now very stable and we have workaround with known VsTest issues.
Should fix #3061.
> fix: Handle Vstest freezes more gracefully

- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/Buildalyzer/AnalyzerResultExtensionsTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs
Running Stryker 4.2.0 CLI on a project containing additional analyzers, will result in an exception as shown in an output below. 
This PR changes the way diagnostics are being parsed to avoid duplicate values.
Steps to reproduce:
```ps1
dotnet new classlib -o "StrykerDemo"
dotnet new nunit -o "StrykerDemo.Tests"
dotnet new sln --name "StrykerDemo"
dotnet sln add .\StrykerDemo\StrykerDemo.csproj
dotnet sln add .\StrykerDemo.Tests\StrykerDemo.Tests.csproj
dotnet add .\StrykerDemo\StrykerDemo.csproj package Antlr4BuildTasks
dotnet add .\StrykerDemo\StrykerDemo.csproj package Antlr4.Runtime
dotnet add .\StrykerDemo.Tests\StrykerDemo.Tests.csproj reference .\StrykerDemo\StrykerDemo.csproj
dotnet stryker
```
Command should result in this kind of an output:
```ps1
_____ _              _ …
```
> fix: Duplicate Analyzer diagnostics

- src/Stryker.Core/Stryker.Core.UnitTest/Compiling/CSharpCompilingProcessTests.cs
- src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs
> fix(reference alias): Properly support PackageReference Alias

- docs/technical-reference/testing-framework.md
I was reading the technical documentation, and came across what seemed like an error in the header level.
Consequently this PR proposes a minor change to the `docs/technical-reference/testing-framework.md` file. The change involves adjusting the heading level for the NUnit section to improve document structure.
> docs: update header level in technical documentation

- src/Stryker.Core/Stryker.Core.UnitTest/Mutants/CsharpMutantOrchestratorTests.cs
- src/Stryker.Core/Stryker.Core/Mutants/CsharpMutantOrchestrator.cs
- src/Stryker.Core/Stryker.Core/Mutants/MutationContext.cs
- src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs
Fix issues with global statements, such as handling of stryker comments and complex mutation declarations (block level).
Declare an orchestrator for global statements. For some reason, the GlobalStatementSyntax class inherits from MemberDefinitionSyntax, which does not lead to the expected behavior: Stryker treats Member Definition as hard barriers.
fix #3081
fix #3073
> fix: Add node orchestrator for global statements

- prepare-release.js
package is a reserved keyword, so SonarQube lists an issue about it: https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&severities=BLOCKER&id=stryker-net
> chore: rename package variable in release script because it's a reserved keyword

- src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
Handle exception raised by VsTest client when calling `AbortSession`.
Fixes #3162.
> fix: Handle VsTest errors on AbortSession

- src/Stryker.Core/Stryker.Core/Initialisation/InitialisationProcess.cs
Before:
> No test result reported. Make sure your test project contains test and is compatible with VsTest.No test detected for project '~/serilog-formatting-log4net/tests/Serilog.Formatting.Log4Net.Tests.csproj'. No cause identified.
After:
> No test result reported. Make sure your test project contains test and is compatible with VsTest.
> Project '~/serilog-formatting-log4net/tests/Serilog.Formatting.Log4Net.Tests.csproj' is using Microsoft.Testing.Platform which is not yet supported by Stryker, see https://github.com/stryker-mutator/stryker-net/issues/3094
> Improve the error when a project is using Microsoft.Testing.Platform

- src/Stryker.CLI/Stryker.CLI/FileConfigReader.cs
Fix typo in exception message when the configuration file doesn't appear to be JSON or YML.
> fix: Typo in exception message

- .github/workflows/integration-test.yaml
- .gitignore
- integration-tests.ps1
- integrationtest/TargetProjects/NetCore/TargetProject/Constructs/CSharp11.cs
- integrationtest/Validation/ValidationProject/ValidateStrykerResults.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/AssignmentStatementMutatorTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/BinaryExpressionMutatorTests.cs
- src/Stryker.Core/Stryker.Core/Mutators/AssignmentStatementMutator.cs
- src/Stryker.Core/Stryker.Core/Mutators/BinaryExpressionMutator.cs
Add support for mutating to/from the [unsigned right-shift operator (`>>>`)](https://learn.microsoft.com/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#unsigned-right-shift-operator-).
| **Original** | **Mutations** |
|:-------------|:--------------|
| `>>`         | `<<`, `>>>`   |
| `<<`         | `>>`, `>>>`   |
| `>>>`        | `<<`, `>>`    |
| `>>=`        | `<<=`, `>>>=` |
| `<<=`        | `>>=`, `>>>=` |
| `>>>=`       | `<<=`, `>>=`  |
> feat(mutating): Mutate unsigned right-shift operator

- integrationtest/TargetProjects/NetCore/TargetProject/Constructs/CSharp11.cs
Fix typo in #3200 that meant that **signed** right shift operators were being tested instead of the _unsigned_ right shift operators 🤦
> chore: Fix integration test

- src/Stryker.Core/Stryker.Core.UnitTest/Mutators/MathMutatorTest.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
- src/Stryker.Core/Stryker.Core/Mutators/MathMutator.cs
Fixes #2933 by using the semantic model to detect calls to System.Math when using `static using`. This ensures `Floor(5.5)` is correctly mutated, just like `Math.Floor(5.5)`.
- Added semantic model checks in both member access and direct call branches.
- Updated MathMutator to handle IdentifierNameSyntax calls to Math methods.
- Verified with a sample C# project using static imports (`FloorValue`, `MixedFloorValue`, etc.).
- Mutation score increased and static calls now generate mutants.
> feat(mutating): Support static using references for Math mutations

- src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/IgnoredMethodMutantFilterTests.cs
- src/Stryker.Core/Stryker.Core/MutantFilters/IgnoredMethodMutantFilter.cs
IgnoreMutantFilter assumes any implicit new construct is part of variable declaration which leads to NRE when this is not the case.
This PR fixes this problem and regression test for this.
Fixes #3257
> fix: Safe parsing of implicit new in IgnoreMutantFilter

- src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
- src/Stryker.CLI/Stryker.CLI/packages.lock.json
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialBuildProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialisationProcessTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InputFileResolverTests.cs
- src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
- src/Stryker.Core/Stryker.Core/Helpers/MsBuildHelper.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InitialBuildProcess.cs
- src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs
- src/Stryker.Core/Stryker.Core/packages.lock.json
- src/Stryker.Options/Stryker.Configuration.csproj
- src/Stryker.Options/packages.lock.json
- src/Stryker.TestRunner.VsTest.UnitTest/packages.lock.json
- src/Stryker.TestRunner.VsTest/Stryker.TestRunner.VsTest.csproj
- src/Stryker.TestRunner.VsTest/packages.lock.json
- src/Stryker.Utilities/Buildalyzer/IAnalyzerResultExtensions.cs
This PR aims at improving Stryker support for complex setup/project situations. As such it:
1. Add a project analysis attempt forcing the target framework when normal attempts failed. This works only when a target framework is defined
2. Ensure Buildalyzer uses the msbuild executable set via the `--msbuild-path` option. This is useful when buildalyzer fails to automatically select the most suitable msbuild version
Issues:
Fixes: #3260
Fixes: #3144
Note: there is unit test for (2) (Buildalyzer using the --msbuild-path`) as its difficult to add. But code is straightforward and I performed manual end-to-end tests on this feature
> feat(build): Improve targetframework and msbuild-path options

- src/Stryker.Core/Stryker.Core.UnitTest/ProjectComponents/SourceProjects/SourceProjectInfoTests.cs
- src/Stryker.Utilities/Buildalyzer/IAnalyzerResultCSharpExtensions.cs
- src/Stryker.Utilities/Buildalyzer/IAnalyzerResultExtensions.cs
Add support for `<DelaySign>` (https://learn.microsoft.com/en-us/cpp/build/reference/delaysign-partially-sign-an-assembly?view=msvc-170) during post-mutation build.
fixes #3272
> feat(compilation): Support projects using DelaySign
