CONTRIBUTING.md
readme.md

Updated readme.md. Still needs a purple or blue (preferably blue) logo.
closes #2 
closes #3

Updated readme.md and contributions.md

---

CONTRIBUTING.md
src/Stryker.CLI/Stryker.CLI.UnitTest/Stryker.CLI.UnitTest.csproj
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/BinaryExpressionMutatorTests.cs
src/Stryker.Core/Stryker.Core/Mutators/BinaryExpressionMutator.cs
src/Stryker.Core/Stryker.Core/Options/StrykerOptionsValidator.cs

Binairy -> Binary

---

src/Stryker.Core/Stryker.Core.UnitTest/Reporters/ConsoleRapportReporterTests.cs
src/Stryker.Core/Stryker.Core/Reporters/ConsoleRapportReporter.cs

Change `mutationscore` to `mutation score` as they are two words

Fix spelling error

---

README.md
src/Stryker.Core/README.md
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/AbstractMutatorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/BooleanMutatorTest.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/PostfixUnaryMutatorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/PrefixUnaryMutatorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
src/Stryker.Core/Stryker.Core/Mutators/AddMutator.cs
src/Stryker.Core/Stryker.Core/Mutators/BooleanMutator.cs
src/Stryker.Core/Stryker.Core/Mutators/PostfixUnaryMutator.cs
src/Stryker.Core/Stryker.Core/Mutators/PrefixUnaryMutator.cs
src/Stryker.Core/Stryker.Core/Options/StrykerOptionsValidator.cs
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj

Implements UnaryExpression mutator #35

Implements UnaryExpression mutator #35

---

src/Stryker.CLI/README.md

Add documentation for config file feature

---

src/Stryker.CLI/README.md

Update readme config file example to use real parametername. timeout-ms --> timeoutMS

Update README.md (timeout-ms)

---

src/Stryker.CLI/README.md
src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFileTests.cs
src/Stryker.CLI/Stryker.CLI.UnitTest/StrykerCLITests.cs
src/Stryker.CLI/Stryker.CLI/CLIOptions.cs
src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs

Test runs are now multithreaded

---

src/Stryker.CLI/README.md
src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFileTests.cs
src/Stryker.CLI/Stryker.CLI.UnitTest/StrykerCLITests.cs
src/Stryker.CLI/Stryker.CLI/CLIOptions.cs
src/Stryker.Core/Stryker.Core.UnitTest/StrykerOptionsTests.cs
src/Stryker.Core/Stryker.Core/Logging/LogOptions.cs
src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs

feat(logging): add logLevel validation

---

src/Stryker.CLI/README.md
src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFileTests.cs
src/Stryker.CLI/Stryker.CLI.UnitTest/StrykerCLITests.cs
src/Stryker.CLI/Stryker.CLI.UnitTest/filled-stryker-config.json
src/Stryker.CLI/Stryker.CLI/CLIOptions.cs

feat: replace camel case arguments with dashed (#100)

---

src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialTestProcessTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialisationProcessTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestExecutorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/DotnetTestRunnerTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/InitialTestProcess.cs
src/Stryker.Core/Stryker.Core/MutationTest/MutationTestExecutor.cs
src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs
src/Stryker.Core/Stryker.Core/TestRunners/DotnetTestRunner.cs
src/Stryker.Core/Stryker.Core/TestRunners/ITestRunner.cs

fix: incorrect test results due to race condition

---

src/Stryker.CLI/README.md
src/Stryker.CLI/Stryker.CLI.UnitTest/StrykerCLITests.cs
src/Stryker.CLI/Stryker.CLI.UnitTest/filled-stryker-config.json
src/Stryker.CLI/Stryker.CLI/CLIOptions.cs
src/Stryker.CLI/Stryker.CLI/OptionsBuilder.cs
src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectFileReaderTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs

fix(logging):Ensure all references of --project are now --project-file

---

RELEASING.md
src/Stryker.CLI/CHANGELOG.md
src/Stryker.Core/CHANGELOG.md

docs: add release procedure

---

README.md
src/Stryker.Core/README.md

Align terminology of Mutator Types #106

---

src/Stryker.CLI/README.md
src/Stryker.CLI/Stryker.CLI.UnitTest/StrykerCLITests.cs
src/Stryker.CLI/Stryker.CLI/Program.cs
src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestProcessTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Reporters/ConsoleReportReporterTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/StrykerTests.cs
src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs
src/Stryker.Core/Stryker.Core/Reporters/ConsoleReportReporter.cs
src/Stryker.Core/Stryker.Core/StrykerRunResult.cs
src/Stryker.Core/Stryker.Core/StrykerRunner.cs

closes #121 
This is one way to return an exit code with the given threshold break.

fix(cli): Return exit code 1 when score is below threshold break value

---

azure-pipelines.yml

build: Add mac os build

---

src/Stryker.Core/Stryker.Core/Reporters/Progress/ConsoleOneLineLogger.cs

fix(reporting): Fix crash on console cursor access on systems that do not have a console available

---

src/Stryker.CLI/Stryker.CLI.UnitTest/Stryker.CLI.UnitTest.csproj
src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj

bump netcoreapp2.0 to netcoreapp2.1

---

CONTRIBUTING.md

Include the commit guidelines as proposed in #275

docs(contributor): Update Contributors Guide

---

integrationtests/IntegrationTests/ExampleProject/StringMagic.cs
src/Stryker.Core/Stryker.Core.UnitTest/Compiling/CompilingProcessTests.cs
src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs
src/Stryker.Core/Stryker.Core/Mutants/MutantPlacer.cs
src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs

Fix(rollback): improve SafeMode

---

azure-pipelines.yml
src/Stryker.CLI/Stryker.CLI.UnitTest/Stryker.CLI.UnitTest.csproj
src/Stryker.CLI/Stryker.CLI.UnitTest/StrykerCLITests.cs
src/Stryker.CLI/Stryker.CLI/CLIOption.cs
src/Stryker.CLI/Stryker.CLI/CLIOptions.cs
src/Stryker.CLI/Stryker.CLI/OptionsBuilder.cs
src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectComponents/ProjectComponentTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestProcessTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Reporters/JsonReporterTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Reporters/ReporterFactoryTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
src/Stryker.Core/Stryker.Core/Initialisation/ProjectComponents/ProjectComponent.cs
src/Stryker.Core/Stryker.Core/Mutants/MutantPlacer.cs
src/Stryker.Core/Stryker.Core/Options/Reporter.cs
src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs
src/Stryker.Core/Stryker.Core/Reporters/BroadcastReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/ConsoleReportReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/JsonReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/ReporterFactory.cs
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
src/Stryker.Core/Stryker.Core/StrykerRunResult.cs

Closes first step of #109 
Closes #277 
Closes #225

feat(json-reporter): Add ability to generate mutation report in json format

---

src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs

Improves handling of case found in #298

fix(project resolver): Check whether found reference equals given project to test

---

azure-pipelines.yml
package.json
src/Stryker.CLI/CHANGELOG.md
src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
src/Stryker.Core/CHANGELOG.md
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj

- StrykerMutator.Core@0.8.0
- StrykerMutator.DotNetCoreCli@0.8.0

Publish 0.8.0

---

azure-pipelines.yml
package.json
src/Stryker.CLI/CHANGELOG.md
src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
src/Stryker.Core/CHANGELOG.md
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj

Reverts stryker-mutator/stryker-net#308

Revert "Publish 0.8.0"

---

src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Progress/ProgressBarReporterTests.cs
src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressBarReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/Progress/StopWatchProvider.cs
src/Stryker.Core/Stryker.Core/Reporters/ReporterFactory.cs

Fix: fix #312 plus relevant regression tests

Fix for #312

---

azure-pipelines-templates/integration-test-steps.yml
azure-pipelines.yml

Cleanup azure-pipelines.yml by using templates

chore(Azure pipelines template): Add templates folder

---

integrationtests/TargetProjects/NetStandard2_0/ExampleProject.XUnit/ExampleProject.XUnit.csproj
src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_IfStatementsShouldBe_Nested_IN.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_IfStatementsShouldBe_Nested_OUT.cs
src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs

Mutate if statements nested to keep the out var scope unchanged
closes #287

fix(Out var breaks stryker): If statements are mutated nested

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutators/LinqMutatorTest.cs
src/Stryker.Core/Stryker.Core/Mutators/LinqMutator.cs

fix(linq mutation): Remove Linq query removal mutation as this changes the return type

---

src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectComponents/ProjectComponentTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Reporters/JsonReporterTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/ProjectComponents/ProjectComponent.cs
src/Stryker.Core/Stryker.Core/Mutants/MutantStatus.cs
src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs
src/Stryker.Core/Stryker.Core/Options/ThresholdOptions.cs
src/Stryker.Core/Stryker.Core/Reporters/JsonReporter/JsonReportComponent.cs

Update json report to be compliant with schema version 0.0.4

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_IfStatementsShouldBe_Nested_IN.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_IfStatementsShouldBe_Nested_OUT.cs
src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs

Fix issues on Declaration pattern + provides location detail when rollback fails.
Changes are minimal

Support DeclarationPattern

---

src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
src/Stryker.Core/Stryker.Core/ToolHelpers/VsTestHelper.cs

chore(vstest-testrunner): Get vstest version from assembly info

---

src/Stryker.Core/README.md
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/LinqMutatorTest.cs
src/Stryker.Core/Stryker.Core/Mutators/LinqMutator.cs

This PR addresses issue https://github.com/stryker-mutator/stryker-net/issues/342.
This is my first PR for this project so hopefully, I didn't miss anything from your [CONTRIBUTING.md](https://github.com/stryker-mutator/stryker-net/blob/master/CONTRIBUTING.md).

feat:(linq-mutator): add linq mutators suggested in #342

---

integrationtest/TargetProjects/BuildFiles/Library.props
integrationtest/TargetProjects/Directory.Build.props
integrationtest/TargetProjects/TargetProject/TargetProject.csproj
src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InputFileResolverTests.cs
src/Stryker.Core/Stryker.Core/Exceptions/StrykerInputException.cs
src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs

Adds support for properties in imported project.
Integration tests were modified in order to cover more complex project setups.
Fixes #317

feat(compiling): Add support for properties in shared projects

---

src/Stryker.Core/Stryker.Core.UnitTest/AssertExtensions.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_KnownComplexCases_IN.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutants/TestResources/Mutator_KnownComplexCases_OUT.cs

PR for issue https://github.com/stryker-mutator/stryker-net/issues/422.
Checks for any diagnostics with severity error in syntax tree of actual syntax node.

test(mutant orchestrator tests):  Check mutant orchestrator tests for syntax errors

---

src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs

fix(Solution path error): Improve solution path error message

---

src/Stryker.Core/Stryker.Core/Initialisation/InitialBuildProcess.cs

Remove logwarning on solution path passed for .net core project

chore(Remove warning): Solution path warning

---

src/Stryker.Core/Stryker.Core/Initialisation/InitialBuildProcess.cs

fix(Solution path exception): Clear error message on solution path missing

---

src/Stryker.Core/Stryker.Core.UnitTest/Reporters/JsonReportTestHelper.cs

Inside nested loop we create 4 FileLeafs with the same file name. I suggest using nested loop variable for filename.

use "y" counter instead of "i" in nested loop in tests

---

src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/NugetRestoreProcessTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/AssignmentStatementMutatorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Progress/ProgressBarReporterTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/NugetRestoreProcess.cs
src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs
src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressBarReporter.cs

fix(Multiple nuget.exe paths): Choose first nuget.exe path found. 

---

src/Stryker.Core/Stryker.Core/Parsers/TotalNumberOfTestsParser.cs

When using Stryker with latest stable dotnet (2.2.300) and NUnit test project (NUnit version 3.11.0), there is an execution error caused by unexpected output format of test execution tool.
The output is expected to contain the line ending with a dot:
`Total tests: 1.`
But so happen that it don't have the dot at the end:
`Total tests: 1`
And Stryker fails wit an error 
```System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
at System.ReadOnlySpan`1.Slice(Int32 start, Int32 length)
at Stryker.Core.Parsers.TotalNumberOfTestsParser.ParseTotalNumberOfTests(String testProcessRunnerOutput) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Parsers\TotalNumberOfTestsParser.cs:line 28
at Stryker.Core.TestRunners.DotnetTestRunner.RunAll(Nullable`1 timeoutMS, …
```

Improved parsing of total number of tests in test result.

---

src/Stryker.Core/Stryker.Core/Initialisation/ProjectInfo.cs

fix(Signed assemblies): Accept relative paths in signed assembly key

---

azure-pipelines.yml
src/Stryker.Core/Stryker.Core/TestRunners/VsTest/RunEventHandler.cs
src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs

feat(vstest.console exceptionhandling): Restart vstest.console and retry testrun on translationlayer exception

---

src/Stryker.Core/Stryker.Core/Reporters/JsonReporter/JsonReport.cs
src/Stryker.Core/Stryker.Core/libman.json

Features:
color: add new color for state no-coverage
emoj: add mutant emoijs
Bug Fixes
legend: status alignments (stryker-mutator/mutation-testing-elements#45)
links: use absolute urls inside the report (stryker-mutator/mutation-testing-elements#56)
popup: caution popup arrow color (stryker-mutator/mutation-testing-elements#46)
popup: popup offset (stryker-mutator/mutation-testing-elements#47)
router: allow url encoded chars in file names (stryker-mutator/mutation-testing-elements#55)

feat(html report): Update html-elements to 1.1.1

---

.dependabot/config.yml

So that it is updated in line with vstest client

deps: Add config pointing to packages.config for vstest

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/LinqMutatorTest.cs
src/Stryker.Core/Stryker.Core/Mutators/LinqMutator.cs

Fix for #704 
Signed-off-by: Cyrille DUPUYDAUBY <dupdob@gmail.com>

Fix: add support for ConditionalExpression to LinqMutator

---

azure-pipelines.yml
pipeline-templates/prepare-integration-test-steps.yml

build(integration test): Push integrationtest package to stryker-net azure artifacts feed for source branches

---

src/Stryker.Core/Stryker.Core/StrykerRunResult.cs

chore: Make StrykerRunResult MutationScore set private

---

src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs

fix(compilation): Compile with AssemblyIdentityComparer compilation option

---

src/Stryker.Core/Stryker.Core.UnitTest/Compiling/RollbackProcessTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs
src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs
src/Stryker.Core/Stryker.Core/Mutators/NegateConditionMutator.cs

fix(mutating): Don't negate IsPatternExpression and properly rollback Accessor methods

---

docs/Reporters.md
src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
src/Stryker.CLI/Stryker.CLI/CLIOptions.cs
src/Stryker.CLI/Stryker.CLI/OptionsBuilder.cs
src/Stryker.CLI/Stryker.CLI/Program.cs
src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
src/Stryker.CLI/Stryker.CLI/packages.lock.json
src/Stryker.Core/Stryker.Core.UnitTest/Reporters/JsonReporterTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Reporters/ReporterFactoryTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs
src/Stryker.Core/Stryker.Core/Reporters/DashboardReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/JsonReporter/JsonMutant.cs
src/Stryker.Core/Stryker.Core/Reporters/JsonReporter/JsonReport.cs
src/Stryker.Core/Stryker.Core/Reporters/JsonReporter/JsonReportFileComponent.cs
src/Stryker.Core/Stryker.Core/Reporters/Reporter.cs
src/Stryker.Core/Stryker.Core/Reporters/ReporterFactory.cs

Adds support for the dashboard reporter.
Add an API key and a project name and version. Then your stryker result will be uploaded to the dashboard and publicly visible.

feat(Dashboard reporter): Support dashboard reporter

---

azure-pipelines.yml
integrationtest/TargetProjects/NetCoreTestProject.XUnit/stryker-config.json
integrationtest/TargetProjects/NetStandardTestProject.XUnit/stryker-config.json
src/Stryker.Core/Stryker.Core.UnitTest/stryker-config.json

build(Nightly run stryker): Update the stryker dashboard every night

---

docs/Configuration.md
docs/Reporters.md
src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs

Fix #900 
Breaks cleartext reporter is no longer default

feat(reporters): Enable Html reporter by default

---

integrationtest/ValidationProject/ValidateStrykerResults.cs
src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestProcessTests.cs
src/Stryker.Core/Stryker.Core/Mutants/MutantStatus.cs
src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs
src/Stryker.Core/Stryker.Core/ProjectComponents/ProjectComponent.cs
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
src/Stryker.Core/Stryker.Core/libman.json

Fixes #885
Includes support for correctly reporting 0 mutants in a file and Ignored mutant status

feat(html reporter): Update to mutation testing elements 1.3.0

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs

I went ahead and made an attempt at fixing the issue I reported in #959.
This is my first time contributing to this project, so let me know if I need to add anything else.
Fixes #959

feat(mutation placing): Add support for mutating static expression bodied constructors

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs

Try and fix the return default bug when the return value is a task

feat(mutation placing): Return default(T) for async Task<T> methods

---

src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
src/Stryker.CLI/Stryker.CLI/StrykerNugetFeedInfo.cs
src/Stryker.CLI/Stryker.CLI/packages.lock.json

fix(update available message): Fix detection of latest stryker version

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs

feat(mutation placing): Return default(T) for all async methods

---

src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs

fix(threshold break score): Diplay the correct mutation score when threshold break is reached

---

src/Stryker.Core/Stryker.Core.UnitTest/StrykerRunResultTests.cs
src/Stryker.Core/Stryker.Core/StrykerRunResult.cs

fix(threshold break): Threshold break calculation should use percentage

---

src/Stryker.Core/Stryker.Core/Mutators/ArrayCreationMutator.cs
src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs

feat(Collection initializer mutator): Also correctly deal with array creation without initializer

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/ArrayCreationMutatorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/InitializerMutatorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/LinqMutatorTest.cs
src/Stryker.Core/Stryker.Core/Mutators/ArrayCreationMutator.cs
src/Stryker.Core/Stryker.Core/Mutators/InitializerMutator.cs

fix(Stackalloc arrays): Mutate stackalloc arrays correctly

---

azure-pipelines.yml
pipeline-templates/prepare-integration-test-steps.yml
src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
src/Stryker.CLI/Stryker.CLI/packages.lock.json
src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
src/Stryker.Core/Stryker.Core/Initialisation/ProjectInfo.cs

Fixes #1076 
The issue was already fixed in #1039 but since it will not be merged before the next release we will merge this seperately.
Tests will be added in #1039

Fix(Define constants bug): Parse defineconstants correctly

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
src/Stryker.Core/Stryker.Core/Mutators/StringMutator.cs

Added check for ConstantPattern to StringMutator
closes #1175

fix(SwitchExpressions): Don't mutate constant value in SwitchExpression

---

docs/Mutators.md
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/LinqMutatorTest.cs
src/Stryker.Core/Stryker.Core/Mutators/LinqMutator.cs

Added linq mutators as proposed in https://github.com/stryker-mutator/stryker-net/issues/1038

feat(Added linq mutator): Added linq Union and intersect mutator.

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core/Mutants/MutantOrchestrator.cs
src/Stryker.Core/Stryker.Core/Mutants/NodeOrchestrators/ConstLocalDeclarationOrchestrator.cs

fix: dont mutate const local declaration

---

src/Stryker.Core/Stryker.Core/Mutants/NodeOrchestrators/ForStatementOrchestrator.cs

chore: Fix forstatementorchestrator for spans

---

docs/Mutators.md
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/LinqMutatorTest.cs
src/Stryker.Core/Stryker.Core/Mutators/LinqMutator.cs

Second PR with suggestions from #1038

feat(Added linq mutator): Added linq Concat and Except mutator.

---

src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InputFileResolverTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/InitialisationProcess.cs
src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs
src/Stryker.Core/Stryker.Core/Initialisation/ProjectInfo.cs
src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs

feat: support .net5 targetframeworks

---

README.md

Since we get issues for our HTML report sometimes

Redirect contributors to mutation-testing-elements

---

src/Stryker.Core/Stryker.Core.UnitTest/Reporters/ClearTextReporterTests.cs
src/Stryker.Core/Stryker.Core/Mutants/Mutant.cs
src/Stryker.Core/Stryker.Core/ProjectComponents/FolderComposite.cs
src/Stryker.Core/Stryker.Core/ProjectComponents/ProjectComponent.cs
src/Stryker.Core/Stryker.Core/Reporters/ClearTextReporter.cs

Creating a textual hierarchy.
Should improve #160

feat(cleartext reporter): Improve directory structure of cleartext console report

---

src/Directory.Build.props
src/Directory.Build.targets
src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/DiffMutantFilterTests.cs
src/Stryker.Core/Stryker.Core/MutantFilters/DiffMutantFilter.cs

fix(git diff filter): Set mutants for unchanged files to Ignored if they have status NotRun

---

src/Stryker.Core/Stryker.Core.UnitTest/Options/ConcurrentTestRunnersOptionsTests.cs
src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs

Fixed `reccomended` typo to `recommended`

---

docs/Introduction.md

Taken from https://github.com/stryker-mutator/stryker-mutator.github.io/blob/0a5080749f789004102c88643ca52a89b26f066e/src/stryker-net/index.pug

docs: add introduction page

---

src/Stryker.RegexMutators/Stryker.RegexMutators.UnitTest/Mutators/QuantifierQuantityMutatorTest.cs
src/Stryker.RegexMutators/Stryker.RegexMutators.UnitTest/Mutators/QuantifierUnlimitedQuantityMutatorTest.cs
src/Stryker.RegexMutators/Stryker.RegexMutators/Mutators/QuantifierQuantityMutator.cs
src/Stryker.RegexMutators/Stryker.RegexMutators/Mutators/QuantifierUnlimitedQuantityMutator.cs
src/Stryker.RegexMutators/Stryker.RegexMutators/RegexMutantOrchestrator.cs

Add mutators for regex greedy quantifier

---

docs/Mutators.md

Docs for https://github.com/stryker-mutator/stryker-net/pull/1276

Add regex quantity mutators to docs

---

docs/Mutators.md
docs/RegexMutators.md

Docs for https://github.com/stryker-mutator/stryker-net/pull/1282

Add look ahead and behind mutators to docs

---

docs/Mutators.md

Website build is broken :( https://github.com/stryker-mutator/stryker-mutator.github.io/runs/1333633540

docs: fix link

---

src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestProcessTests.cs
src/Stryker.Core/Stryker.Core/MutationTest/MutationProcess.cs

fix(filter mutants): do not pass Compile Error mutants to filters (#1295)

---

src/Stryker.Core/Stryker.Core.UnitTest/DashboardCompare/GitInfoProviderTests.cs
src/Stryker.Core/Stryker.Core/DashboardCompare/GitInfoProvider.cs

fix(dashboard compare): verify the name of target branch

---

src/Stryker.Core/Stryker.Core.UnitTest/DiffProviders/GitDiffProviderTests.cs
src/Stryker.Core/Stryker.Core/DiffProviders/GitDiffProvider.cs

fix(diff): improve the change test filter

---

src/Stryker.Core/Stryker.Core/Initialisation/InitialBuildProcess.cs

feat(initial-build): Improve error message when initial build fails

---

src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialBuildProcessTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/InitialBuildProcess.cs

feat(initial-build): Allow solutionpath for dotnet core

---

integrationtest/TargetProjects/NetCoreTestProject.XUnit/stryker-config.json
integrationtest/TargetProjects/TargetProject/Person.cs
integrationtest/TargetProjects/TargetProject/Student.cs
src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/FilePatternMutantFilterTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/StrykerRunnerTests.cs
src/Stryker.Core/Stryker.Core/MutantFilters/FilePatternMutantFilter.cs
src/Stryker.Core/Stryker.Core/MutantFilters/MutantFilterFactory.cs
src/Stryker.Core/Stryker.Core/StrykerRunner.cs

fixes #1377
Added a integration test for this so it won't be refactored out again...
Also tested the file filter on solution run feature. It works fine again :)

fix(MutantFilters): Fix refactor issue where mutant filters were not called

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core/Mutants/NodeOrchestrators/AccessorSyntaxOrchestrator.cs
src/Stryker.Core/Stryker.Core/Mutants/NodeOrchestrators/BaseMethodDeclarationOrchestrator.cs
src/Stryker.Core/Stryker.Core/Mutants/NodeOrchestrators/BlockScopeOrchestrator.cs
src/Stryker.Core/Stryker.Core/Mutants/NodeOrchestrators/PropertyDeclarationOrchestrator.cs

fix: mutations may leak between body formed methods/properties (#1368)

---

src/Stryker.Core/Stryker.Core/Reporters/HtmlReporter/HtmlReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/JsonReporter/JsonReporter.cs

feat(reports): Clickable report urls in terminal

---

src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs

fix: Copy git diff enabled option to project specific option

---

src/Stryker.Core/Stryker.Core/ProjectComponents/FolderComposite.cs

fix(solution run): Fix NPE on solution runs

---

src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InputFileResolverTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs

As agreed, this doesn't implement the option itself, just a minimal API change.

feat(multi-target): Prepare project analyzer for multi-target support

---

src/Stryker.Core/Stryker.Core.UnitTest/AssertExtensions.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Mutators/StatementMutatorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Options/StrykerOptionsTests.cs
src/Stryker.Core/Stryker.Core/Mutants/CsharpMutantOrchestrator.cs
src/Stryker.Core/Stryker.Core/Mutators/Mutator.cs
src/Stryker.Core/Stryker.Core/Mutators/StatementMutator.cs

feat(statement mutator): Add mutator that removes statements

---

src/Stryker.Core/Stryker.Core.UnitTest/Baseline/Providers/AzureFileShareBaselineProviderTests.cs
src/Stryker.Core/Stryker.Core/Baseline/Providers/AzureFileShareBaselineProvider.cs

fix(baseline): Allow valid version strings like 2.0.0

---

src/Stryker.Core/Stryker.Core/ToolHelpers/VsTestHelper.cs

I didn't run into any of these issues when running the package gotten from NuGet, but rather had them in local development.
* Look in `$HOME` in addition to `$USERPROFILE` (for UNIX-systems)
* Use `netcoreapp2.1` instead of `netcoreapp2.0`
* 2.0 has reached end-of-life, so this should be ok, right?
* Ignore case when looking at embedded vstest resource names
* I faced this issue before I noticed we should look in `$HOME` also, and had ran the manual `dotnet restore`, which is used in CI

Fix issues with resolving vstest location

---

src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/ThresholdBreakInputTests.cs
src/Stryker.Core/Stryker.Core/Options/Inputs/ThresholdBreakInput.cs

#1519 applied to the new options branch

Allow 100 break threshold, update break input tests

---

src/Stryker.Core/Stryker.Core/ToolHelpers/VsTestHelper.cs

Pull request #1518 fixed the discovery of the vstest console inside the NuGet packages directory for macOS and Linux. This commits work on top of it to make it even more future-proof.
* Safer because the `netcoreapp2.1` and `net451` target framework monikers are not hardcoded anymore so it becomes more future-proof if Microsoft ever updates those.
* Simpler because it uses `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile` instead of probing both `USERPROFILE` and `HOME` environment variables.

dev: Simpler vstest.console discovery on *nix

---

src/Stryker.CLI/Stryker.CLI.UnitTest/CLIOptionsTests.cs
src/Stryker.CLI/Stryker.CLI/CLIOptions.cs

and fix default value for ignore-methods

ShouldHaveDefaultValues should have a fact

---

src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InputFileResolverTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs

fix(Dotnet 5 support): net5.0 version parsing

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutants/MutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core/Helpers/RoslynHelper.cs

Add proper support to conversion operator and fix issue #1612

Support conversion operator

---

src/Stryker.CLI/Stryker.CLI.UnitTest/Stryker.CLI.UnitTest.csproj
src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/DashboardMutantFilterTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
src/Stryker.Core/Stryker.Core/Initialisation/InitialBuildProcess.cs
src/Stryker.Core/Stryker.Core/MutationTest/MutationTestExecutor.cs
src/Stryker.Core/Stryker.Core/Mutators/RegexMutator.cs
src/Stryker.Core/Stryker.Core/Reporters/BroadcastReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/ConsoleDotProgressReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/HtmlReporter/HtmlReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/JsonReporter/JsonReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/ReporterFactory.cs
src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs
src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunnerPool.cs
src/Stryker.Core/Stryker.Core/Testing/ProcessResult.cs
src/Stryker.RegexMutators/Stryker.RegexMutators.UnitTest/Stryker.RegexMutators.UnitTest.csproj

This pull requests silences various sonarcloud issues. It also includes a clean up of the csproj files that contained a mix of tabs and spaces.

Sonarcloud fixes

---

src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs
src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs

feat: C# Source Generators
Implements support for C# Source Generators as observed in the Roslyn source.

Added support for C# source generators.

---

azure-pipelines.yml
package.json
prepare-release.js
src/Stryker.CLI/Stryker.CLI/Clients/StrykerNugetFeedClient.cs
src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
src/Stryker.DataCollector/Stryker.DataCollector/Stryker.DataCollector.csproj

chore(Pre releases): prepare scripts for pre releases

---

src/Directory.Build.props
src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
src/Stryker.CLI/Stryker.CLI/packages.lock.json
src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
src/Stryker.Core/Stryker.Core/packages.lock.json
src/Stryker.DataCollector/Stryker.DataCollector/packages.lock.json
src/Stryker.RegexMutators/Stryker.RegexMutators.UnitTest/packages.lock.json
src/Stryker.RegexMutators/Stryker.RegexMutators/packages.lock.json

build: Enable reproducible builds and sourcelink

---

docs/configuration.md
src/Stryker.CLI/Stryker.CLI/CommandLineConfigHandler.cs
src/Stryker.CLI/Stryker.CLI/FileBasedInput.cs
src/Stryker.CLI/Stryker.CLI/JsonConfigHandler.cs
src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/TargetFrameworkResolutionTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/TargetFrameworkInputTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs
src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs
src/Stryker.Core/Stryker.Core/Options/Inputs/TargetFrameworkInput.cs
src/Stryker.Core/Stryker.Core/Options/StrykerInputs.cs
src/Stryker.Core/Stryker.Core/Options/StrykerOptions.cs

Okay so 1.0 is out and I want to address the biggest pain we have :D 
This implementation works but I haven't added tests yet as I want to verify if this the right direction and if this fits the new options approach.
If we merge this I will go try Stryker 1.0 in action!

Added an option to specify target framework

---

src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InputFileResolverTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs

Fixes #1686.
Does not address [documentation restructuring proposal](https://github.com/stryker-mutator/stryker-net/issues/1686#issuecomment-920447827) by @philrowan-mtb mentionned in #1686. I'd be glad to work on that proposal, as long as it's agreed with maintainers.

chore: Remove references to --project-file from Stryker.Core

---

src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
src/Stryker.CLI/Stryker.CLI/Clients/StrykerNugetFeedClient.cs
src/Stryker.CLI/Stryker.CLI/packages.lock.json
src/Stryker.Core/Stryker.Core.UnitTest/Baseline/Providers/DashboardBaselineProviderTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Clients/DashboardClientsTest.cs
src/Stryker.Core/Stryker.Core.UnitTest/Reporters/DashboardReporterTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Reporters/HtmlReporterTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Reporters/JsonReporterTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
src/Stryker.Core/Stryker.Core/Baseline/Providers/DashboardBaselineProvider.cs
src/Stryker.Core/Stryker.Core/Clients/DashboardClient.cs
src/Stryker.Core/Stryker.Core/Reporters/DashboardReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/JsonReporter/JsonReport.cs
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
src/Stryker.Core/Stryker.Core/packages.lock.json

See [Sending and Receiving JSON using HttpClient with System.Net.Http.Json][1] by Steve Gordon for a great explanation.
[1]: https://www.stevejgordon.co.uk/sending-and-receiving-json-using-httpclient-with-system-net-http-json

chore: Use System.Net.Http.Json for efficient JSON over HTTP

---

src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs

By using `AssemblyInformationalVersionAttribute` we have access to the full semantic version, including the release tag (e.g. `rc3`).
Before this commit:
```
_____ _              _               _   _ ______ _______  
/ ____| |            | |             | \ | |  ____|__   __| 
| (___ | |_ _ __ _   _| | _____ _ __  |  \| | |__     | |    
\___ \| __| '__| | | | |/ / _ \ '__| | . ` |  __|    | |    
____) | |_| |  | |_| |   <  __/ |    | |\  | |____   | |    
|_____/ \__|_|   \__, |_|\_\___|_| (_)|_| \_|______|  |_|    
__/ |                                      
|___/                                       
Version: 1.0.0
```
After this commit:
```
_____ _              _               _   _ ______ _______  
/ ____| |            | |             | \ | |  ____|__   __| 
| (___ | |_ _ __ _ …
```

fix: Show full version number at startup

---

package.json
prepare-release.js
src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj

fix(version undefined): Remove version suffix "undefined" from stryker version

---

docs/mutations.md

chore: Update mutations docs

---

README.md

Now they are too big for the amount of content there :D

Docs: aligning header sizes in the README

---

src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/IgnoredMethodMutantFilterTests.cs

chore: Add test for ignore method

---

src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/ReportersInputTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/WithBaselineInputTests.cs
src/Stryker.Core/Stryker.Core/Options/Inputs/ReportersInput.cs
src/Stryker.Core/Stryker.Core/Options/StrykerInputs.cs

fix(options): Auto enable baseline reporter when baseline is enabled.

---

docs/configuration.md
src/Stryker.CLI/Stryker.CLI/CommandLineConfig/CommandLineConfigHandler.cs

fix #1779 
@psfinaki and @richardwerkman Is this solution acceptable to you?

feat(options): Reintroduce threshold high and threshold low from the commandline

---

integrationtest/TargetProjects/TargetProject/Student.cs
src/Stryker.CLI/Stryker.CLI/CommandLineConfig/CommandLineConfigHandler.cs
src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/DiffMutantFilterTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/ExcludeMutationMutantFilterTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/FilePatternMutantFilterTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/MutantFilterFactoryTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/SinceMutantFilterTests.cs
src/Stryker.Core/Stryker.Core/MutantFilters/BroadcastMutantFilter.cs
src/Stryker.Core/Stryker.Core/MutantFilters/DashboardMutantFilter.cs
src/Stryker.Core/Stryker.Core/MutantFilters/ExcludeFromCodeCoverageFilter.cs
src/Stryker.Core/Stryker.Core/MutantFilters/ExcludeLinqExpressionFilter.cs
src/Stryker.Core/Stryker.Core/MutantFilters/ExcludeMutationMutantFilter.cs
src/Stryker.Core/Stryker.Core/MutantFilters/FilePatternMutantFilter.cs
src/Stryker.Core/Stryker.Core/MutantFilters/IMutantFilter.cs
src/Stryker.Core/Stryker.Core/MutantFilters/IgnoredMethodMutantFilter.cs
src/Stryker.Core/Stryker.Core/MutantFilters/MutantFilter.cs
src/Stryker.Core/Stryker.Core/MutantFilters/MutantFilterFactory.cs
src/Stryker.Core/Stryker.Core/MutantFilters/SinceMutantFilter.cs

fix(since): Mutants ignored from source code comment are no longer re-enabled by the since filter

---

src/Stryker.CLI/Stryker.CLI.UnitTest/filled-stryker-config.json
src/Stryker.CLI/Stryker.CLI/FileBasedInput.cs
src/Stryker.CLI/Stryker.CLI/JsonConfigHandler.cs

fix(Config file): Remove check for additional properties on base object config file

---

src/Stryker.CLI/Stryker.CLI.UnitTest/filled-stryker-config.json
src/Stryker.CLI/Stryker.CLI/JsonConfigHandler.cs

feat(Config file comments): Add support for config file comments

---

src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
src/Stryker.CLI/Stryker.CLI/packages.lock.json
src/Stryker.Core/Stryker.Core.UnitTest/ToolHelpers/BuildalyzerHelperTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs
src/Stryker.Core/Stryker.Core/Initialisation/CsharpProjectComponentsBuilder.cs
src/Stryker.Core/Stryker.Core/Reporters/DashboardReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/HtmlReporter/HtmlReporter.cs
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
src/Stryker.Core/Stryker.Core/packages.lock.json

Also add nice hint for opening the report
closes #1828

fix(Load preprocessor symbols): Correctly load preprocessor symbols so they can be used

---

src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
src/Stryker.CLI/Stryker.CLI/packages.lock.json
src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
src/Stryker.Core/Stryker.Core/packages.lock.json

fix: mutation testing for self-contained apps

---

azure-pipelines.yml
src/Directory.Build.props
src/Stryker.CLI/Stryker.CLI.UnitTest/Stryker.CLI.UnitTest.csproj
src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
src/Stryker.RegexMutators/Stryker.RegexMutators.UnitTest/Stryker.RegexMutators.UnitTest.csproj
src/Stryker.RegexMutators/Stryker.RegexMutators.UnitTest/packages.lock.json

ci: Use coverlet instead of Microsoft.Coverage

---

src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/IgnoredMethodMutantFilterTests.cs
src/Stryker.Core/Stryker.Core/MutantFilters/IgnoredMethodMutantFilter.cs

Fix the regression in Stryker.Net 1.3 with ignoredmethod filter.
Regression tests have been aded

fix: stackoverflow exceptions due to ignoredmethods filter

---

src/Stryker.Core/Stryker.Core.UnitTest/Compiling/CompilingProcessTests.cs
src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs

make sure mutations are only rolled back once. Added regression test
see issue #1937

Fix Null Reference Exception during mutation rollback

---

package.json
prepare-release.js
src/Stryker.CLI/CHANGELOG.md
src/Stryker.Core/CHANGELOG.md

chore(Changelog generation): Changelogs were missing version numbers

---

src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
src/Stryker.CLI/Stryker.CLI/packages.lock.json
src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj

fix(packaging): Include referenced projects in nupkg

---

src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs
src/Stryker.Core/Stryker.Core/ProjectComponents/Solution.cs

Solution runs still won't work after this. But at least it doesn't show any errors.

fix(Solution run): Fix several issues with solution runs

---

docs/ignore-mutations.md

Fixes [#1991](https://github.com/stryker-mutator/stryker-net/issues/1991)

Docs: link to list of the types of ignorable mutators

---

src/Stryker.Core/Stryker.Core.UnitTest/DashboardCompare/GitInfoProviderTests.cs
src/Stryker.Core/Stryker.Core/Baseline/Providers/GitInfoProvider.cs

In addition to a branch or a commit.

fix(since): Add possibility to specify a git tag for the since.target option

---

src/Stryker.CLI/Stryker.CLI.UnitTest/ConfigFileTests.cs
src/Stryker.CLI/Stryker.CLI/Logging/ApplicationLogging.cs

fix(reporting): Set correct log level for libgit2sharp

---

src/Stryker.Core/Stryker.Core/Baseline/Providers/AzureFileShareBaselineProvider.cs

fix(baseline): fixed issue where invalid header was used for creating azure fileshare file

---

src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/TargetFrameworkResolutionTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs

Adds a simple catch for if no analyzerResults are found.

fix(initialisation): Improve error message when no analyzer results are found

---

docs/mutations.md

Changes \\| to | on mutations page:
https://stryker-mutator.io/docs/stryker-net/mutations/

Changes \| to | on mutations page.

---

src/Stryker.Core/Stryker.Core/Reporters/HtmlReporter/HtmlReporter.cs
src/Stryker.Core/Stryker.Core/Reporters/Json/JsonReporter.cs

fix(Console print): Escape paths with Spectre.Console to prevent Exception

---

CONTRIBUTING.md
adding_a_mutator.md

docs: Add documentation step to contribution guides

---

adding_a_mutator.md

docs: Fix contributing link in add a mutator docs

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutants/CsharpMutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core/Mutants/CsharpMutantOrchestrator.cs
src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/PrefixUnaryExpressionOrchestrator.cs

fix(PrefixUnaryExpression mutator): Handle mutations of prefixed increment/decrement

---

src/Directory.Packages.props
src/Stryker.CLI/Stryker.CLI.UnitTest/Stryker.CLI.UnitTest.csproj
src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
src/Stryker.CLI/Stryker.CLI/packages.lock.json
src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
src/Stryker.Core/Stryker.Core/packages.lock.json

chore(deps): update dependencies system.io.abstractions to v19

---

src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs
src/Stryker.Core/Stryker.Core/Initialisation/EmbeddedResourcesGenerator.cs

fix(embedded resources generation): Use buildalyzer to find root namespace and embedded resources

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutators/StringMutatorTests.cs
src/Stryker.Core/Stryker.Core/Mutators/StringMutator.cs

fix(StringMutator): Don't mutate strings in Guid ctor

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutators/StringEmptyMutatorTests.cs
src/Stryker.Core/Stryker.Core/Mutators/StringEmptyMutator.cs

closes #2446 
Tested manually just to be sure.

Added extra parens to new string mutations

---

src/Stryker.Core/Stryker.Core.UnitTest/Compiling/CompilingProcessTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs

feat(compiling): signing key is not required even if SignAssembly is…set to true

---

src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/InitialTestProcessTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/ProjectMutatorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/FullRunScenario.cs
src/Stryker.Core/Stryker.Core.UnitTest/MutationTest/MutationTestExecutorTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/TestRunners/VsTestMockingHelper.cs
src/Stryker.Core/Stryker.Core/MutationTest/MutationTestExecutor.cs
src/Stryker.Core/Stryker.Core/TestRunners/TestRunResult.cs
src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs

feat: Add trace logging with vstest console messages

---

src/Stryker.Core/Stryker.Core/Clients/DashboardClient.cs
src/Stryker.Core/Stryker.Core/DiffProviders/GitDiffProvider.cs
src/Stryker.Core/Stryker.Core/FilePattern.cs
src/Stryker.Core/Stryker.Core/Helpers/TypeBasedStrategy.cs
src/Stryker.Core/Stryker.Core/InjectedHelpers/CodeInjection.cs
src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/PostfixUnaryExpressionOrchestrator.cs
src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestDescription.cs

hi
this should fix 6 out of the 7 remaining.
the last one is a todo that I think should remain. At least, I am not sure what it means, hence I can't deal with it 😄

chore: Fix remaining sonar issues

---

docs/getting-started.md

chore(docs): convert link to image

---

src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Html/Realtime/SseServerTest.cs
src/Stryker.Core/Stryker.Core.UnitTest/Reporters/JsonReporterTests.cs
src/Stryker.Core/Stryker.Core/Reporters/Json/JsonReport.cs
src/Stryker.Core/Stryker.Core/Reporters/Json/TestFiles/JsonTestFile.cs
src/Stryker.Core/Stryker.Core/Reporters/Json/TestFiles/Test.cs
src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestDescription.cs

fix: exception when source files in more than one test project

---

src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Html/Realtime/SseServerTest.cs
src/Stryker.Core/Stryker.Core/Reporters/Html/Realtime/SseServer.cs

Clean up the design of SSE server tests so that they are no longer flaky

chore: stabilize SSE tests

---

docs/configuration.md
docs/mutations.md

We don't mutate constants, right? Inspired by [this question](https://stackoverflow.com/q/76495189/3232646) BTW.

docs: We don't mutate constants

---

docs/getting-started.md

I don't think many users will be coming from 0.x now. And this is more future proof

chore: Update getting-started.md

---

src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs

Provide details when buildalyzer fails to analyze a project/solution

feat(buildalyzer): Provide msbuild log when buildalyzer fails analysis

---

adding_a_mutator.md

Added an extra space so the text is in italics.

docs(adding_a_mutator): fix minor markdown issue

---

src/Stryker.Core/Stryker.Core.UnitTest/MutantFilters/IgnoredMethodMutantFilterTests.cs
src/Stryker.Core/Stryker.Core/MutantFilters/IgnoredMethodMutantFilter.cs

Enable filtering null-conditional method invocations by name

---

.editorconfig

- Refactor entire solution to file-scoped namespaces
- Bump language version of data collector project and also refactor to file-scoped namespaces
Relates to #2470, will be fixed in a later change.

chore: add suggestion for file-scoped namespaces to editorconfig

---

README.md

chore: Add mutation score badge to readme

---

src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/TargetFrameworkResolutionTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs
src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs

fix: Use solution file when it's available

---

src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs

Improve error and trace logging around unrecoverable compilation failures

chore(compilation): Improve Error and Trace Logging

---

src/Stryker.Core/Stryker.Core/InjectedHelpers/MutantControl.cs

fix: Remove usings from MutantControl

---

docs/configuration.md

Added necessary configuration for SAS. Resolves #2676 
Hope this small contribution for the hacktoberfest helps and the label `hacktoberfest-accepted` will be added.

docs: add SAS configuration (#2676)

---

src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultCSharpExtensions.cs
src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs

chore: Splitting some C# related extensions in a separate file

---

docs/configuration.md
src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/SinceInputTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/Options/StrykerInputsTests.cs
src/Stryker.Core/Stryker.Core/Options/Inputs/SinceInput.cs

feat(baseline): Validate mutual exclusivity of explicit --since and --with-baseline options

---

docs/configuration.md

Needed for https://github.com/stryker-mutator/stryker-mutator.github.io/pull/719

chore: update configuration.md

---

src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs

This results in cleaner log when an analyzer fails to load.
Address #2785

Fix: Do not throw when an analyzer fails to load

---

src/Directory.Packages.props
src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
src/Stryker.CLI/Stryker.CLI/packages.lock.json
src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/Buildalyzer/AnalyzerResultExtensionsTests.cs
src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
src/Stryker.Core/Stryker.Core/Compiling/CSharpRollbackProcess.cs
src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultCSharpExtensions.cs
src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs
src/Stryker.Core/Stryker.Core/packages.lock.json

feat: Support compiler diagnostic options from msbuild

---

docs/configuration.md

I forgot to add documentation for the new init command

chore: add documentation for init

---

src/Stryker.Core/Stryker.Core.UnitTest/Reporters/Html/RealTime/Events/SseEventTest.cs
src/Stryker.Core/Stryker.Core/Reporters/Html/RealTime/Events/SseEvent.cs

fix(real time reporting): Whitespace in report data no longer removed

---

src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/Buildalyzer/AnalyzerResultExtensionsTests.cs
src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs

fix: Stryker fails if project has conflicting settings regarding warnings

---

docs/stryker-in-pipeline.md

The pipeline docs were missing this info IMO

docs: Update stryker-in-pipeline.md

---

src/Stryker.Core/Stryker.Core.UnitTest/Mutants/CsharpMutantOrchestratorTests.cs
src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/AnonymousFunctionExpressionOrchestrator.cs

fix: Support mutating anonymous methods (a.k.a delegate) properly

---

src/Stryker.Core/Stryker.Core/Mutants/BaseMutantOrchestrator.cs
src/Stryker.Core/Stryker.Core/Mutants/CsharpMutantOrchestrator.cs
src/Stryker.Core/Stryker.Core/Mutants/CsharpNodeOrchestrators/BaseFunctionOrchestrator.cs
src/Stryker.Core/Stryker.Core/Mutants/MutantPlacer.cs

Alternative fix for concurrency issue. See #2899

Fix Concurrency issue with MutantPlacer (alt version)

---

src/Directory.Packages.props
src/Stryker.CLI/Stryker.CLI.UnitTest/Stryker.CLI.UnitTest.csproj
src/Stryker.CLI/Stryker.CLI.UnitTest/packages.lock.json
src/Stryker.CLI/Stryker.CLI/packages.lock.json
src/Stryker.Core/Stryker.Core.UnitTest/Stryker.Core.UnitTest.csproj
src/Stryker.Core/Stryker.Core.UnitTest/packages.lock.json
src/Stryker.Core/Stryker.Core/Stryker.Core.csproj
src/Stryker.Core/Stryker.Core/packages.lock.json

Perfom manual update for Buildalyzer

chore(deps): update dependency buildalyzer to v7

---

docs/mutations.md

docs: Replace mention of exclude-mutations with ignore-mutations

---

src/Stryker.Core/Stryker.Core.UnitTest/Options/Inputs/AzureFileStorageSasInputTests.cs
src/Stryker.Core/Stryker.Core/Options/Inputs/AzureFileStorageSasInput.cs

Improve handling of azure-fileshare-sas configuration string
Fix #2725

fix: Strengthen azure sas parsing

---

src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestContextInformation.cs

Closes #2990
This adds some logging to point the user to the problem with test discovery.
It also addresses an issue where invalid XML was being sent to VsTest
(If there are any issues with this PR, please feel free to push commits directly to my branch to resolve them)

fix: Escape test case filter before passing to VsTest

---

docs/mutations.md

Fixed so mutators are in alphabetical order

docs: Update mutations.md with alphabetical order

---

src/Stryker.Core/Stryker.Core/Initialisation/EmbeddedResourcesGenerator.cs

Fix #3071
Fix #3088
Fix #3090
It is a naive fix (using a concurrent dictionnary instead of normal one). As far as I understand the code, the remaining risk is loading twice some resource in case of concurrent access. I do not think this will be an issue.
A proper fix is to ensure access to the cache is exclusive (at least for the writing part), which require more code and testing (especially) that I feel this issue warrants.
But I could be convinced to provide a better implementation 😉.

fix(embedded resources): Use concurrent dictionnary for resource cache

---

src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs

Use concurrent aware collections for the dynamic list of discovered projects (during analysis)
Fix issues #3108

fix: make project discovery concurrent compatible

---

src/Stryker.Core/Stryker.Core.UnitTest/ProjectComponents/SourceProjects/SourceProjectInfoTests.cs
src/Stryker.Utilities/Buildalyzer/IAnalyzerResultCSharpExtensions.cs

fix: Set default nullable compilation option to disable

---

.github/copilot-instructions.md
.github/instructions/azure-devops-pipelines.instructions.md
.github/instructions/conventional-commit.instructions.md
.github/instructions/csharp.instructions.md
.github/instructions/github-actions-ci-cd-best-practices.instructions.md
.github/instructions/markdown.instructions.md
.github/instructions/security-and-owasp.instructions.md
.github/instructions/self-explanatory-code-commenting.instructions.md
.github/instructions/taming-copilot.instructions.md
CONTRIBUTING.md

Move instruction files into .github folder

chore: Update Copilot instructions
